Makefile

Makes use of conda-build's Python via the [environment variable it sets]( https://docs.conda.io/projects/conda-build/en/latest/user-guide/environment-variables.html#environment-variables-set-during-the-build-process ). Default to the first `python3` if nothing else can be found.

Use conda-build's Python

---

tests/multiple-listener-client-test.py
tests/multiple-listener-test.py
ucp_py/_libs/src/ucp_py_ucp_fxns.c

- used to be the case that ucp_context was associated with just one listener_context that was getting overwritten with contents of a new listener that was created
- enabling separate listener contexts per ucp context now (but limiting to 256 listeners)

fixing bugs with multiple listeners case

---

tests/test_port.py
ucp/_libs/ucp_py.pyx

@mrocklin @quasiben 
Getting port information from UCX may take time. Refer https://github.com/openucx/ucx/issues/3534
Will the logic included in this PR suffice for now? 
Example usage:
```python
In [1]: import ucp
In [2]: ucp.init()
Out[2]: 0
In [3]: import asyncio
In [4]: loop = asyncio.get_event_loop()
In [5]: async def talk_to_client(ep, listener):
...:     recv_req = await ep.recv_future()
...:     recv_msg = ucp.get_obj_from_msg(recv_req)
...:     print('client connected')
...:     ucp.destroy_ep(ep)
...: 
In [6]: listener = ucp.start_listener(talk_to_client, listener_port=0, is_coroutine=True)
In [7]: coro = listener.coroutine
In [8]: listener.port
Out[8]: 49038
In [9]: loop.run_until_complete(coro)
client connected
```
```python
In [1]: import ucp
In [2]: import asyncio
In [3]: …
```

assign random port to listener if port=0 passed

---

tests/send-recv-py-obj.py
tests/test_timeout.py
ucp/_libs/src/ucp_py_ucp_fxns.c
ucp/_libs/ucp_py.pyx

- if client appears before server which listens, this PR allows the client to wait for `UCXPY_CONN_RETRY_PERIOD` seconds, and retry connection establishment for a maximum of `EP_CONN_MAX_RETRIES` attempts.
```
akvenkatesh@prm-dgx-10:~/ucx-py$ UCXPY_CONN_RETRY_PERIOD=2 UCX_MEMTYPE_CACHE=n UCX_RNDV_SCHEME=put_zcopy python3 tests/send-recv-py-obj.py -o cupy -s IP -p 13337
[1558033604.520057] [prm-dgx-10:81187:1]   rdmacm_iface.c:401  UCX  ERROR received event RDMA_CM_EVENT_UNREACHABLE. status = 1. Peer: IP:13337.
connection failed. Retrying in 2 seconds
[1558033606.523174] [prm-dgx-10:81187:1]   rdmacm_iface.c:401  UCX  ERROR received event RDMA_CM_EVENT_UNREACHABLE. status = 1. Peer: IP:13337.
connection failed. Retrying in 2 seconds
[1558033608.526044] [prm-dgx-10:81187:0] …
```

Retry connection establishment

---

tests/test_send_recv_obj.py
ucp/_utils.py

Until now, `test_send_recv_obj` has only checked 2-byte transfers which stresses just the `eager` protocol. This PR adds 4MB transfers to stress `rendezvous` protocol.
cc @jakirkham

augment test_send_recv_obj with large message transfers

---

tests/test_send_recv_obj.py
ucp/_utils.py

PR cleans up tests
- no longer send all objects as cupy arrays in make_server
- adds dtype tests
- adds large data test

Cleanup tests

---

ucp/_libs/ucp_py.pyx
ucp/_libs/ucp_py_buffer_helper.pyx

Previously we would only use the first dimension in a Message shape
in the __getbuffer__ method.  This would result in poorly formed memoryview
objects.
Fixes https://github.com/rapidsai/ucx-py/issues/119

Use full shape in buffer protocol

---

ucp/_libs/ucp_py_buffer_helper.pyx

This reworks PR ( https://github.com/rapidsai/ucx-py/pull/120 )'s changes slightly to drop the hard NumPy requirement added by it. Fixing an issue encountered when building the ucx-py packages.

Drop hard numpy requirement

---

tests/test_buffer_region.py
ucp/_libs/ucp_py.pyx
ucp/_libs/ucp_py_buffer_helper.pyx

`len(memoryview.shape)` might not equal `memoryview.ndim`
All tests in `tests/test_buffer_region.py ` now passes on my installation
**Update:** the returned shape and strides in `__buffer__` is now allocated on the heap.

[MERGE] Fixes wrong shape and stack allocation in BufferRegion

---

tests/test_custom_ep_send_recv.py

In cudf 0.10 indicies are properly serialized to deviceNDArray.  This PR fixes the custom test where cudf testing is done
cc @Akshay-Venkatesh

Fix Custom Test

---

tests/test_buffer_region.py
ucp/_libs/ucp_py.pyx
ucp/_libs/ucp_py_buffer_helper.pyx

This PR simply adds some constructors to the `BufferRegion` class. 
The is a step on the way to make `BufferRegion` only constructable through constructors.

Implements BufferRegion Constructors

---

README.md

Appears these conda package install instructions got lost in some recent restructuring of the README. This readds them. Though please recheck to make sure this still keeps everything added from the recent restructuring.

Restore the conda package install docs

---

LICENSE
MANIFEST.in
setup.cfg

Copies over the OpenUCX license file and ensures it is included in various Python packages that may be produced.
Fixes https://github.com/rapidsai/ucx-py/issues/123

Include license file

---

tests/test_multiple_nodes.py
tests/test_send_recv.py
ucp/_libs/core.pyx
ucp/_libs/send_recv.pyx

Previously we used asyncio features that were only available in Python 3.7
This commit replaces those calls with options that are also available in 3.6

Support Python 3.6

---

tests/test_config.py
tests/test_multiple_nodes.py
tests/test_send_recv.py
tests/test_shutdown.py
tests/utils.py
ucp/__init__.py
ucp/_libs/core.pyx
ucp/_libs/core_dep.pxd
ucp/_libs/utils.pyx
ucp/_version.py
ucp/public_api.py
versioneer.py

Added `ucp.get_config()` that returns a `dict` of the current UCX configuration e.g.:
```python
{   'UCX_ACC_DEVICES': 'all',
'UCX_ADAPTIVE_PROGRESS': 'y',
'UCX_ALLOC_PRIO': 'md:sysv,md:posix,huge,thp,md:*,mmap,heap',
'UCX_ATOMIC_MODE': 'guess',
'UCX_BCOPY_BW': '5800M',
'UCX_BCOPY_THRESH': '0',
'UCX_FLUSH_WORKER_EPS': 'y',
'UCX_MAX_EAGER_RAILS': '1',
'UCX_MAX_RNDV_RAILS': '2',
'UCX_MAX_WORKER_NAME': '32',
'UCX_MEMTYPE_CACHE': 'n',
'UCX_NET_DEVICES': 'all',
'UCX_NUM_EPS': 'auto',
'UCX_NUM_PPN': 'auto',
'UCX_RNDV_FRAG_SIZE': '256K',
'UCX_RNDV_PERF_DIFF': '1.000',
'UCX_RNDV_SCHEME': 'auto',
'UCX_RNDV_SEND_NBR_THRESH': '256K',
'UCX_RNDV_THRESH': 'auto',
'UCX_RNDV_THRESH_FALLBACK': 'inf',
'UCX_SEG_SIZE': '8K',
'UCX_SELF_DEVICES': 'all',
'UCX_SHM_DEVICES': 'all',
'UCX_SOCKADDR_AUX_TLS': …
```

[REVIEW] UCX Configuration in Python

---

setup.py

By default setuptools knows how to handle Cython extensions and will try to build them through Cython or fallback to compiling C files (if available).

Rely on setuptools' support of Cython

---

ucp/_libs/core.pyx
ucp/_libs/core_dep.pxd

Now cleaning up UCX context and worker in `ApplicationContext.__dealloc__()`

UCX context and worker cleanup

---

ucp/_libs/core.pyx
ucp/_libs/send_recv.pyx
ucp/_libs/utils.pyx

Relaxes the requirement on NumPy where possible. Leverages fixed size C arrays when it makes sense. Drops an unneeded NumPy import. Also rescopes a NumPy import to the section of code where it is needed.

Relax NumPy requirement

---

setup.py
tests/test_config.py
ucp/_libs/core.pyx
ucp/_libs/core_dep.pxd
ucp/exceptions.py
ucp/public_api.py

Fixes #83.
This makes it possible to specify UCX options programmable using `ucp.init()`:
```python
def init(options={}, env_takes_precedence=False):
"""
Initiate UCX. Usually this is done automatically at the first API call
but this function makes it possible to set UCX options programmable.
Alternatively, UCX options can be specified through environment variables.
Parameters
----------
options: dict, optional
UCX options send to the underlaying UCX library
env_takes_precedence: bool, optional
Whether environment variables takes precedence over the `options`
specified here.
"""
```
cc @pentschev, @mrocklin

UCX Options Programmable 

---

ucp/_libs/core.pyx

Fixes https://github.com/rapidsai/ucx-py/issues/210
Fixes https://github.com/rapidsai/ucx-py/issues/223
Merges https://github.com/rapidsai/ucx-py/pull/228
Merges https://github.com/rapidsai/ucx-py/pull/230
Creates a `struct` called `Tags` to hold the different tag values when sending or receiving them. Should make it easier to follow which tag is being used where.

Use struct tags

---

ucp/__init__.py
ucp/_libs/core.pyx

This PR combines the communication tags into `msg_tag` and `ctrl_tag`, which fixes a problem when a Endpoint connects to itself: https://github.com/rapidsai/ucx-py/pull/215#discussion_r333047909
Also, the logging now uses the address of the underlying `ucp_ep_h` as the Endpoint ID, which is the same as UCX uses thus making it easier to follow the interplay between UCX and UCX-Py

Combining communication tags

---

tests/test_multiple_nodes.py
ucp/_libs/core.pyx

Fixes #234 by implementing `Endpoint.ucx_info()`:
```python
def ucx_info(self):
"""Return low-level UCX info about this endpoint as a string"""
```
cc  @cjnolet

Endpoint.ucx_info(): low-level UCX info

---

tests/test_shutdown.py
ucp/_libs/core.pyx
ucp/public_api.py

This PR fixes https://github.com/rapidsai/ucx-py/issues/235 and fixes #219 by moving `Endpoint` and `Listener` to `public_api.py`

Consistent separation of public vs private API 

---

setup.py

Fixes https://github.com/rapidsai/ucx-py/issues/258
This flag no longer has any effect on the compilation process of ucx-py after the rewrite. So go ahead and drop this flag.

Drop the now irrelevant `--with-prof` flag

---

setup.py

Merges https://github.com/rapidsai/ucx-py/pull/260
Merges https://github.com/rapidsai/ucx-py/pull/261
Fixes https://github.com/rapidsai/ucx-py/issues/258
Fixes https://github.com/rapidsai/ucx-py/issues/259
Consolidates the changes to remove `--with-prof` and `--with-cuda` flags from the custom `build_ext`. Also goes ahead and removes the custom `build_ext` class entirely. After all it doesn't appear to have a use after removing both of these.

Drops outdated build flags from `build_ext`

---

ucp/_libs/core.pyx
ucp/_libs/send_recv.pyx

Unless I am doing something wrong, it seams that UCX will connect a worker with itself even when sending to another endpoint.
This PR reintroduces different send/recv tags that should fix https://github.com/dask/distributed/pull/3135 
To see the problem, use the #246 PR to print extra information and run `UCXPY_LOG_LEVEL=DEBUG pytest tests -vsx`. Some runs should result in similar results as:
```
================================================================================================= FAILURES =================================================================================================
_______________________________________________________________________________________ test_send_recv_numpy[<i8-16] ______________________________________________________________________________ …
```

Differentiating send/recv tags

---

ucp/_libs/core.pyx
ucp/_libs/core_dep.pxd

When Python's `asyncio` library wake-up the UCX worker, we have to re-arm it using [`ucp_worker_arm`](http://openucx.github.io/ucx/api/v1.5/html/group___u_c_p___w_a_k_e_u_p.html#gadce97937294aae0f5f599d58d68904d6).

Re-arming the UCX worker after each wakeup

---

tests/test_version.py
ucp/__init__.py
ucp/_libs/core.pyx
ucp/public_api.py

This PR implements  `ucp.get_ucx_version()` and `ucp.__ucx_version__`.

Get UCX version

---

README.md

Fixes https://github.com/rapidsai/ucx-py/issues/241
Fixes https://github.com/rapidsai/ucx-py/issues/257
Fixes https://github.com/rapidsai/dask-cuda/issues/159
Updates the `conda-forge` packages to be used when performing development builds. Also updates the instructions for installing prebuilt Conda packages.
cc @quasiben @mrocklin @VibhuJawa

Update Conda commands in README

---

tests/test_ucx_getters.py
ucp/public_api.py

Fix #117 and fix #130, including tests

Python getters to the underlying UCP objects

---

ucp/_libs/core.pyx

This allows setting `UCX_TLS=all` to support CUDA, instead of passing all options individually.
cc @quasiben

Ensure "all" is a valid TLS value to enable CUDA

---

tests/test_reset.py
tests/test_shutdown.py
tests/test_version.py
ucp/_libs/core.pyx
ucp/_libs/core_dep.pxd
ucp/public_api.py

This PR fixes many resource leaks and makes `ucp.reset()` raise an exception if the `ApplicationContext` is still referenced by `Endpoint` and `Listener` objects. If that is the case, we cannot safely shutdown UCX.

Fixing UCX leaks and safe UCX shutdown

---

tests/test_guarantee_msg_order.py
ucp/_libs/core.pyx
ucp/_libs/send_recv.pyx
ucp/_libs/utils.pyx
ucp/public_api.py

This PR implements a `guarantee_msg_order` argument when creating Endpoints, which UCX tag messaging [doesn't guarantees](https://github.com/dask/distributed/pull/3135#issuecomment-545480041).

Guarantee Message Order

---

tests/test_shutdown.py
ucp/_libs/core.pyx
ucp/public_api.py

This PR makes sure that when a Endpoint receive the shutdown signal it delays the shutdown to after all inflight messages has been received.
Also, this PR implements `Endpoint.close_after_n_recv()`:
```python
def close_after_n_recv(self, n, count_from_ep_creation=False):
"""Close the endpoint after `n` received messages.
Parameters
----------
n: int
Number of messages to received before closing the endpoint.
count_from_ep_creation: bool, optional
Whether to count `n` from this function call (default) or
from the creation of the endpoint.
"""
if not count_from_ep_creation:
n += self._ep._finished_recv_count  # Make `n` absolute
if self._ep._close_after_n_recv is not None:
raise exceptions.UCXError(
"close_after_n_recv() is already set to: %d (abs)"
% self._ep._close_after_n_recv
)
if n == …
```

Flushing before shutdown

---

setup.py

Fixes https://github.com/rapidsai/ucx-py/issues/299
This renames the package to `ucxpy` like the PyPI name that we claimed.

Rename package to ucxpy

---

benchmarks/recv-into-client.py
docs/source/quickstart.rst
tests/test_custom_send_recv.py
tests/test_reset.py
tests/test_send_recv.py
tests/test_shutdown.py
ucp/_libs/core.pyx
ucp/public_api.py

Instead of `close()` and `async signal_shutdown()`, we now have:
```python
def abort(self):
"""Close the communication immediately and abruptly.
Useful in destructors or generators' ``finally`` blocks.
Notice, this functions doesn't signal the connected peer to close.
To do that, use `Endpoint.close()`
"""
async def close(self):
"""Close the endpoint cleanly.
This will attempt to flush outgoing buffers before actually
closing the underlying UCX endpoint.
"""
```

Cleanup the closing of endpoint

---

README.md

Minor README change for cudf-build instructions (ass missing `git submodule update --init --remote --recursive`).

Add cudf submodule update command in README

---

ci/gpu/build.sh
docs/source/install.rst

It's complex regardless, but this way we stop people from
installing cudatoolkit, and give them a copy-pasteable solution in
the CPU-only case.

Split installation documentation to CPU/GPU sections

---

ucp/__init__.py

Set `UCX_CUDA_IPC_CACHE=n` upon ucp import to prevent memory leaks when NVLink is enabled (see https://github.com/openucx/ucx/issues/4410).
Using `ucp.init` to do this is currently not possible as it only supports UCP configurations and `UCX_CUDA_IPC_CACHE` is part of UCT, which is considerably more complex to query/set, as it requires traversing all MDs and interfaces.

Set UCX_CUDA_IPC_CACHE=n upon ucp import

---

benchmarks/local-send-recv.py
ci/gpu/build.sh

This PR implements a send-recv benchmark targeting a single machine with multiple GPUs.
```
$ local-send-recv.py --help
usage: local-send-recv.py [-h] [-n BYTES] [--n-iter N] [-o {numpy,cupy}] [-v]
[-s ip] [-d N] [-e N] [--reuse-alloc]
[--cuda-profile]
Roundtrip benchmark
optional arguments:
-h, --help            show this help message and exit
-n BYTES, --n-bytes BYTES
Message size. Default '10 Mb'.
--n-iter N            Numer of send / recv iterations (default 10).
-o {numpy,cupy}, --object_type {numpy,cupy}
In-memory array type.
-v, --verbose         Whether to print timings per iteration.
-s ip, --server-address ip
Server address (default `ucp.get_address()`).
-d N, --server-dev N  GPU device on server (default 0).
-e N, --client-dev N  GPU device on client (default 0).
--reuse-alloc …
```

Send-recv benchmark for a local machine

---

ci/gpu/build.sh
conda/environments/builddocs_py37.yml
setup.py
tests/test_topological_distance.py
ucp/_libs/core.pyx
ucp/_libs/src/topological_distance.c
ucp/_libs/src/topological_distance.h
ucp/_libs/src/topological_distance_sample.c
ucp/_libs/topological_distance.pyx
ucp/_libs/topological_distance_dep.pxd

This will help applications such as dask-cuda identify the closest InfiniBand device to a GPU.
Note that I only added one test and that requires either to be running on a DGX-1 or DGX-2. Since these changes are very much hardware dependent, I don't know if we could have a test to run on generic hardware. Ideas for a test like that are welcome.

Add TopologicalDistance class to identify closest devices to a GPU

---

ucp/__init__.py

As far as I can see, we always have to set `UCX_SOCKADDR_TLS_PRIORITY=sockcm` in order to run on multiple nodes. And since there isn't any drawback?, let's set it as default.
Notice, I am setting the option as an environment variable. It is possible to set it as a UCX option but I think this is more readable.

Setting UCX_SOCKADDR_TLS_PRIORITY=all as default

---

README.md
ci/gpu/build.sh
docs/source/install.rst
docs/source/quickstart.rst

Updates the docs to point to the `rapidsai` channel for packages.

Use rapidsai Conda packages

---

README.md
docs/source/install.rst

As the install instructions are mostly in the docs anyways, this fills in some missing details in the docs and removes them from the README in the spirit of DRY. Should keep things easier to maintain. Discussion on this would be very welcome.

Move install instructions out of README

---

ucp/__init__.py

It turns out that `UCX_SOCKADDR_TLS_PRIORITY=all` doesn't work in the general case. We need to set `UCX_SOCKADDR_TLS_PRIORITY=sockcm`.
Since [`LocalCUDACluster`](https://github.com/rapidsai/dask-cuda/blob/97f485d1f449b9d6a45d79a86971d604d458cfa2/dask_cuda/local_cuda_cluster.py#L64) doesn't sets it by default and `DGX` is deprecated, it will fail for a new user.

[Critical] Setting UCX_SOCKADDR_TLS_PRIORITY=sockcm

---

docs/source/install.rst

Depends on PR ( https://github.com/rapidsai/ucx-split-feedstock/pull/6 )
Make sure to mention `libibcm` in the install doc's system level requirements.

Add `libibcm` to the install docs

---

setup.py
tests/test_run_on_local_network.py
ucp/utils.py

This PR implements `utils.run_on_local_network()`, which spawns, connects, and runs a number of workers.
```python
def run_on_local_network(
n_workers, worker_func, worker_args=None, server_address=None, ucx_options_list=None
):
"""
Creates a local UCX network of `n_workers` that runs `worker_func`
Parameters
----------
n_workers : int
Number of workers (nodes) in the network.
worker_func: callable (can be a coroutine)
Function that each worker execute. 
Must have signature: `worker(rank, eps, args)` where
- rank is the worker id
- eps is a dict of ranks to ucx endpoints
- args given here as `worker_args`
worker_args: object
The argument to pass to `worker_func`.
server_address: str
Server address for the workers. If None, get_address() is used.
ucx_options_list: list of dict
Options to …
```

Create and run local network

---

docs/source/configuration.rst
docs/source/glossary.rst
docs/source/index.rst

PR updates TLS options and adds a glossary page for the many acronyms in the UCX/networking ecosystem
Thanks to @hiroyuki-sato for the supplying the [glossary](https://github.com/hiroyuki-sato/openucx-docs/)

add glossary page and update more TLS config options

---

ucp/_libs/core.pyx

This PR makes ucxpy request `UCP_FEATURE_WAKEUP` always.
In principle the wake up feature is not required when in non-blocking mode; we are not using any of the [UCX wake-up routines](http://openucx.github.io/ucx/api/v1.5/html/group___u_c_p___w_a_k_e_u_p.html).
But on a DGX-1 using InfiniBand I see the following error when not requesting `UCP_FEATURE_WAKEUP`:
```
$ UCXPY_NON_BLOCKING_MODE=1 python  cudf-merge.py -c 10000000 --devs=0,6 --net-devices=auto
[1576760097.195101] [dgx15:48168:0]   cuda_copy_ep.c:63   UCX  ERROR Failed to allocate cuda event object
[1576760097.195138] [dgx15:48168:0]   cuda_copy_ep.c:63   UCX  ERROR Failed to allocate cuda event object
[1576760097.195147] [dgx15:48168:0]   cuda_copy_ep.c:63   UCX  ERROR Failed to allocate cuda event object
[1576760097.195155] …
```

Request UCP_FEATURE_WAKEUP always

---

ucp/_libs/core_dep.pxd

As UCX defines a `*` with a `struct` type and then `*_h` as a pointer to that `struct`, correct the definitions in `core_dep.pxd` to accordingly.
1. Make `ucp_ep` a `struct` and `ucp_ep_h` a pointer
2. Make `ucp_context` a `struct` and `ucp_context_h` a pointer
3. Make `ucp_worker` a `struct` and `ucp_worker_h` a pointer
ref1: https://github.com/openucx/ucx/blob/v1.6.1/src/ucp/api/ucp_def.h#L83
ref2: https://github.com/openucx/ucx/blob/v1.6.1/src/ucp/api/ucp_def.h#L51
ref3: https://github.com/openucx/ucx/blob/v1.6.1/src/ucp/api/ucp_def.h#L231

Define `*_h` types as pointers to `struct`s

---

ucp/_libs/core.pyx
ucp/_libs/core_dep.pxd
ucp/_libs/send_recv.pyx
ucp/_libs/utils.pyx

Follow the convention in other RAPIDS Cython code of using `uintptr_t` as an intermediate when coercing a Python `int` to a C pointer or vice versa.

Use `uintptr_t` to coerce to/from Python `int`s & C pointers

---

ucp/_libs/core.pyx
ucp/_libs/send_recv.pyx

Ensure Cython recognizes these function pointers match the expected callback type by explicitly casting them to that type. This becomes more important when trying to release the GIL in these code sections. As Cython seems to not recognize these are function pointers and not Python objects.

Cast callback function pointers to expected type

---

ci/gpu/build.sh
docs/source/install.rst
ucp/_libs/core_dep.pxd
ucp/_libs/utils.pyx

As Cython supplies `PyMemoryView_GET_BUFFER` in its API as of 0.29.14+, simplify the code by using their API. Make a few more simplifications to `_data_from_memoryview` so that it can be simply inlined.

Simplify PyMemoryView_GET_BUFFER call

---

benchmarks/local-send-recv.py

This adds an option to use RMM in the `local-send-recv` benchmark. This still uses CuPy arrays. However under-the-hood allocations are backed by an RMM pool. Initially the pool is empty, but grows to accommodate our needs.

Add option to use RMM with local-send-recv

---

ucp/__init__.py

Using a CUDA memory pool with the CUDA IPC cache doesn't cause an OOM error, this is because the pool should not release/reallocate of memory during runtime.
Given that our most common use case today comprises the use of an RMM pool, we may reenable this to facilitate users' life. It's still possible to disable the cache by setting the environment variable `UCX_CUDA_IPC_CACHE=n`, and this may be required for any uses cases that do not include the use of a memory pool at the risk of running OOM otherwise.

Use default UCX_CUDA_IPC_CACHE value again

---

tests/test_send_recv_two_workers.py

As `DeviceBuffer` requires arguments passed to its constructor are keyword arguments, make sure to pass `size` as a keyword argument as well.

Pass `size` as keyword argument to `DeviceBuffer`

---

setup.py

The package name is `ucx-py` for both [rapidsai](https://anaconda.org/rapidsai/ucx-py) and [conda-forge](https://anaconda.org/conda-forge/ucx-py) channels, therefore I think renaming it is good to make things consistent.

Rename package to ucx-py in setup.py

---

ucp/_libs/core.pyx

This PR fixes https://github.com/rapidsai/ucx-py/issues/413 by making sure that asyncio's next state after calling `ucp_worker_arm()` is epoll wait.

[Merge] Epoll wait follows worker arming 

---

docs/source/configuration.rst

From the wiki, this appears to be named `UCX_RNDV_THRESH`. So have updated it here. However not totally sure about this. So please check.

Correct UCX_RNDV_THRESH environment variable name

---

ucp/_libs/core.pyx
ucp/_libs/send_recv.pyx

Make sure any Python exceptions from `cdef` functions with non-Python return types are being propagated upwards.

Mark sure Python exceptions get raised

---

tests/test_send_recv_two_workers.py
tests/utils.py

Fixed `CUDA_VISIBLE_DEVICES`  access in `test_send_recv_cu`

two-worker-test: fixed CUDA_VISIBLE_DEVICES

---

ci/gpu/build.sh

It is simply not reliable to run in CI

CI: ignoring the two worker tests

---

ucp/_libs/core_dep.pxd
ucp/_libs/send_recv.pyx

This PR makes sure that when modifying a future, the event loop used when creating the future is open.

Make sure we use the right event loop when modifying futures

---

ci/gpu/build.sh
conda/environments/builddocs_py37.yml
docs/source/install.rst

`psutil` was introduced as a dependency in https://github.com/rapidsai/ucx-py/pull/423, but it was not updated as such, this PR addresses it.

Add psutil as a dependency

---

ucp/_libs/core.pyx
ucp/public_api.py

This PR makes sure that the shutdown order of Context, Endpoints, and Listeners is correct.
Context now has a weak reference to all _child_ objects and makes sure to abort them before destroying the UCX context.

Cleaning up the shutdown of Context, Endpoint, and Listener

---

setup.py

Try to use Cython's `new_build_ext` (planned to replace it's current `build_ext`) in order to benefit from features (like parallel builds). Though maintain a fallback to Setuptools in cases where Cython might not be present as needed for building (like checking the version). Note Setuptools would like to adopt this behavior in the future, but hasn't yet ( https://github.com/pypa/setuptools/issues/1270 ).

Use Cython's `new_build_ext` (if available)

---

ucp/_libs/ucx_api.pyx

As it sounds like `initialized` should be visible externally, but should not be modifiable. This makes makes it `readonly` so that it can be checked in external usage, but not changed.
cc @pentschev @madsbk

Mark `initialized` as `readonly`

---

ucp/_libs/core.pyx

In some dask workflows we occasionally get an error like the following:
>   File "ucp/_libs/core.pyx", line 640, in close
AttributeError: 'NoneType' object has no attribute 'progress'
Thus far I've only been able to generate this error when using multiple nodes and IB with the following reproducer:
```python
from distributed import Client
client = Client("ucx://...")
client.upload_file('file.txt')
```
I still don't understand why things are happening this way, but it seems like ucx-py or ucx has already closed/aborted the endpoint by the time ucx-py gets to the  cython `close` function.  At this point, the worker is None and is unable to call `progress`.   This PR moves the progess call under `else` so it is only called if the try succeeds without exception

Closing Fixes

---

ucp/_libs/core.pyx

This PR makes sure that an endpoint only tells peer to shutdown once.
This PR should also fix the close issue seen in https://github.com/rapidsai/ucx-py/pull/473. 
@quasiben, can you to confirm that you don't see the error?:
File "ucp/_libs/core.pyx", line 640, in close
AttributeError: 'NoneType' object has no attribute 'progress'

Endpoint: shutdown peer once

---

ucp/continuous_ucx_progress.py

It's still unclear whether this is the right solution or if it impacts performance, but it potentially resolves #480 . When running Dask+UCX-Py with `python -X dev` we keep seeing `ValueError: the socket must be non-blocking` being thrown during `BlockingMode._fd_reader_callback`, which calls `ucp_worker_progress` .

Set rsock/wsock to blocking

---

ucp/_libs/core.pyx

Implementing `exchange_peer_info()` using the `struct` module instead of cython's struct.
This PR is part of the effort to restrict the use of Cython to `ucx_api.pyx`

Implementing exchange_peer_info() using struct

---

ucp/_libs/core.pyx
ucp/_libs/ucx_api.pyx
ucp/utils.py

NVTX annotations add a new row `ucxpy` to profiles, identifying `send`/`recv`/`progress` calls. See example below:

Add NVTX annotations

---

ucp/core.py

We don't need the asyncio error handler anymore. Now it only seems to hide debug information.

Remove asyncio exception handler

---

ucp/core.py

Fixed wrong indentation in `Endpoint.abort()`, which made the endpoint not close if there wasn't any outstanding messages :flushed:

Fixed wrong indentation in abort of an endpoint

---

ucp/core.py

This PR disable `guarantee_msg_order` by default.
The message order is guaranteed by UCX itself so is shouldn't be needed in UCX-Py.
Before we merge, let's make sure this doesn't break downstream libraries.
cc. @pentschev, @quasiben

Disabling guarantee_msg_order by default

---

tests/test_multiple_nodes.py
ucp/core.py

UCX hangs when many clients (~100) call `ep_create()` without any call to `progress()` in between.
This PR adds a test of the case and fix the hang by calling `progress()` right after the call to `ep_create()`, which is probably a good idea in any case.

Progress after endpoint create

---

ucp/_libs/ucx_api.pyx
ucp/_libs/ucx_api_dep.pxd
ucp/core.py

This PR make sure that all calls to the UCX is using valid UCX handles and streamlines the destruction of UCX handles.

Streamlining the destructors in the UCX API

---

ucp/core.py

Reorders `exchange_peer_info` operations based on whether the endpoint is a listener or client endpoint.
This seems to fix the `ValueError("Both peers must set guarantee_msg_order identically")` exception being raised when workers start creating endpoints to each other. In 10 IB+NVLink runs on 4 nodes (32 GPUs) that exception wasn't raised a single time, nor did I experience hangs. Without changes here I would see the exception every run and it would hang about 50% of the time.

Reorder `exchange_peer_info` send/recv operations

---

ucp/core.py

This PR seems to fix an issue when using dask's `c.upload_file`.  We thought we had resolved with https://github.com/rapidsai/ucx-py/pull/473 and https://github.com/rapidsai/ucx-py/pull/477 .  I am still a bit confused as to what is happening and why this PR "fixes" things when really the code in the `finally` block should have no issue
cc @VibhuJawa @pentschev

[WIP] Upload_File Fix

---

conda/environments/builddocs_py37.yml

As `sphinx-markdown-tables` is now in `conda-forge`, just use the package from there.

Use `sphinx-markdown-tables` from conda-forge

---

ci/local/README.md
ci/local/build.sh

This script is designed for developer and contributor use. This tool mimics the actions of gpuCI on your local machine. This allows you to test and even debug your code inside a gpuCI base container before pushing your code as a GitHub commit. The script can be helpful in locally triaging and debugging RAPIDS continuous integration failures.

[REVIEW] Local gpuCI build script

---

ucp/continuous_ucx_progress.py
ucp/utils.py

Running Python in debug mode reveals the following warnings:
```python
/datasets/pentschev/src/ucx-py/tests/debug-tests/test_send_recv_many_workers.py:54: ResourceWarning: unclosed <socket.socket fd=33, family=AddressFamily.AF_INET, type=SocketKind.SOCK_DGRAM, proto=0, laddr=('0.0.0.0', 0)>
addr = ucp.get_address()
```
```python
/datasets/pentschev/miniconda3/envs/pydbg-102-0.14.0b200521/lib/python3.8/site-packages/ucp/core.py:197: ResourceWarning: unclosed <socket.socket fd=42, family=AddressFamily.AF_UNIX, type=SocketKind.SOCK_STREAM, proto=0>
progress_tasks.clear()
```
This PR ensures those sockets are closed before destroying them.

Ensure sockets are closed

---

docs/source/configuration.rst
docs/source/dask.rst
docs/source/index.rst

PR corrects naming style of UCX-Py
cc @pentschev

Use UCX-Py in docs [skip ci]

---

tests/debug-tests/test_send_recv_many_workers.py

This test currently fails without the RMM pool enabled. So mark it as an xfailing test. We can always selectively enable it if we wish to explore/debug it further.
xref: https://github.com/rapidsai/ucx-py/issues/531

Mark many worker send/recv as xfail without RMM

---

tests/debug-tests/test_endpoint_error_callback.py
ucp/_libs/src/c_util.c
ucp/_libs/src/c_util.h
ucp/_libs/ucx_api.pyx
ucp/_libs/ucx_api_dep.pxd
ucp/core.py

This PR uses the `UCP_ERR_HANDLING_MODE_PEER` mode by default for InfiniBand endpoints, preventing a UCX process from exiting with a fatal error should an issue occur. This mode isn't currently supported by UCX with the TCP transport, therefore no callback is added should the `UCX_TLS` not contain `dc`, `ib` or `rc`. It's also possible to prevent endpoints and listeners from using this mode by passing `endpoint_error_handling=False`.
As future work, we may want to add some mechanism to enforce `UCXEndpoint` to be destroyed once an error occurs and the callback is executed. This seems currently not necessary in Dask, once can test this only with IB enabled and kill a worker in the middle of a task and a new one will spawn without any other processes exiting with a fatal error. I'm not yet …

Add endpoint error handler

---

ucp/core.py

When the error handler is enabled, there's no NVLink transfers happening even with `cuda_ipc`. This PR disables the error handler by default until we can sort out why that happens.

Disable endpoint error handling by default

---

tests/test_libs_utils.py

Needed for PR ( https://github.com/rapidsai/ucx-py/pull/546 )
Adds some tests for the utility functions `get_buffer_data` and `get_buffer_nbytes` using both Python builtin objects and NumPy/CuPy arrays. Should exercise both the `memoryview` case as well as the `__array_interface__`/`__cuda_array_interface__` case.

Test `get_buffer_data` and `get_buffer_nbytes`

---

benchmarks/cudf-merge.py
benchmarks/local-send-recv.py
debug-tests/client.py
debug-tests/debug_utils.py
debug-tests/server.py
debug-tests/test_send_recv_many_workers.py
examples/cupy-example.py
setup.cfg
setup.py
tests/debug-tests/test_endpoint_error_callback.py
tests/test_config.py
tests/test_custom_send_recv.py
tests/test_disconnect.py
tests/test_guarantee_msg_order.py
tests/test_libs_utils.py
tests/test_multiple_nodes.py
tests/test_reset.py
tests/test_run_on_local_network.py
tests/test_send_recv.py
tests/test_send_recv_two_workers.py
tests/test_shutdown.py
tests/test_tags.py
tests/test_topological_distance.py
tests/test_ucx_getters.py
tests/utils.py
ucp/_libs/ucx_api.pyx
ucp/_libs/utils.pyx

Fixed `isort` error in CI like this [one](https://gpuci.gpuopenanalytics.com/blue/organizations/jenkins/rapidsai%2Fgpuci%2Fucx-py%2Fprb%2Fucx-py-style/detail/ucx-py-style/722/pipeline). 
Apparently, `THIRDPARTY` must be defined under `sections`. We now use the same order as [cuDF]( https://github.com/rapidsai/cudf/blob/6dc286ba67d2ec7e73674351be7011604b7a2fe7/python/cudf/setup.cfg#L15)

Use the isort setup as cuDF

---

docs/source/install.rst

As shells may be confused by `>`, `<`, etc., quote the version specifications to ensure this is interpreted correctly.

Quote version constrained requirements in install docs

---

ucp/endpoint_reuse.py

This PR implements a workaround of https://github.com/openucx/ucx/issues/3192 by introducing `EndpointReuse`:
```python
class EndpointReuse:
"""
Class to seamlessly reuse endpoints. It uses the tag feature of send/recv
to separate "virtual" endpoint pairs from each other.
Connection Protocol
-------------------
1) Client connect to server using a new endpoint.
2) Client send the IDs of all its existing endpoints.
3) Server receives the IDs from the client and checks if it has a
matching existing endpoint. It then sends the matching ID to the
client or zero if no match.
4) The client and server now continue with either the existing matching
endpoints or the new endpoints (which are registered for later reuse).
"""
```

Endpoint Reuse

---

ci/local/build.sh

PR fixes local docker image `(DOCKER_IMAGE` string) used by build script:
- Programmatically inserts minor version num
- Replaces py3.6 with py3.7 (in line with dropping Python 3.6 support for v0.15 -> https://github.com/rapidsai/ops/issues/1017)

[REVIEW] update docker image [skip-ci]

---

ucp/_libs/utils.pyx

Attempt to make error more descriptive to the missing `ucx-proc=*=gpu` package.

Mention ucx-proc=*=gpu in CUDA error message

---

tests/test_custom_send_recv.py

Previously we were using Dask's `assert_eq`, which caused some issues when testing with cuDF's new nullable support. Here we fix this by relying on cuDF's `assert_eq`, which is designed to handle cuDF objects that we are passing.
cc @pentschev @quasiben

Use cuDF's `assert_eq`

---

ci/gpu/build.sh
setup.py

Cleans up requirements on CI.
* Use `ucx` package instead of building from source
* Drop/consolidate dependencies

Fix-up CI requirements

---

ci/gpu/build.sh

Make sure we are running the PyTorch tests on CI so we can catch any regressions here.

Run PyTorch tests from Distributed on CI

---

ucp/_libs/__init__.pxd
ucp/_libs/topological_distance.pyx
ucp/_libs/ucx_api.pyx
ucp/_libs/utils.pxd
ucp/_libs/utils.pyx

Rewrites buffer utility functions to get more optimizations out of Cython. This includes typing variables where possible, leveraging `for`-loops that are easier for Cython to lower to C, making use of Cython `memoryview`s, and some code simplification (where possible).
cc @pentschev @madsbk @quasiben

Optimize buffer utility functions

---

ci/release/update-version.sh
docs/source/conf.py

Fixes [a linting error]( https://gpuci.gpuopenanalytics.com/blue/organizations/jenkins/rapidsai%2Fgpuci%2Fucx-py%2Fprb%2Fucx-py-style/detail/ucx-py-style/808/pipeline/ ) observed in PR ( https://github.com/rapidsai/ucx-py/pull/574 ).

Fix doc style

---

ucp/_libs/topological_distance.pxd
ucp/_libs/topological_distance.pyx

Adds a `.pxd` file for `topological_distance`. Types methods arguments and variables in methods. Drops some casts where the type was unchanged.

Some cleanup of topological distance

---

ci/gpu/build.sh

This entire computation uses a bit under 2 MB of space. So bump the pool size so that all the allocations should fit comfortably within it.
xref: https://github.com/rapidsai/ucx-py/issues/578#issuecomment-674309920
cc @quasiben

Use 2 MB pool for cuDF merge

---

ucp/_libs/ucx_api.pyx

Go ahead and type `handle_as_int` as `uintptr_t` in the function signature, Cython already knows how to convert generic Python `int`s to `uintptr_t` without intervention. Plus it simplifies the code internally.

Type `handle_as_int` as `uintptr_t` in signature

---

docs/source/install.rst

When https://github.com/rapidsai/ucx-split-feedstock/pull/40 is merged we should have docs on how to build UCX properly for IB/RDMA support

Include docs on building IB/RDMA support

---

ucp/_libs/ucx_api_dep.pxd

This PR removes unecessary references to master or updates references to the new main branch in CI scripts and other OPS-owned files.

[REVIEW] Update docs to remove references to master [skip ci]

---

ucp/_libs/utils.pyx

Streamlines the C-code generated by Cython for `get_buffer_data` to avoid unnecessary code generation.
<hr>
A short benchmark can be seen below. Makes a small, but notable improvement to the `__cuda_array_interface__` case. The `memoryview` case is [unchanged from before]( https://github.com/rapidsai/ucx-py/pull/592#issuecomment-683166572 ). The previous benchmark with CuPy can be seen [here]( https://github.com/rapidsai/ucx-py/pull/546#issuecomment-673614364 ).
```python
In [1]: import cupy
...: import numpy
...: 
...: from ucp._libs.utils import get_buffer_data, get_buffer_nbytes
In [2]: s = (10, 11, 12, 13)
...: a_c = numpy.arange(numpy.prod(s)).reshape(s)
...: a_g = cupy.arange(numpy.prod(s)).reshape(s)
In [3]: %timeit get_buffer_data(a_c)
548 ns ± 4.85 ns per loop (mean ± std. dev. …
```

Further streamline `get_buffer_data`

---

tests/test_libs_utils.py
ucp/_libs/utils.pyx

As we already have a branch later for the CUDA case, defer checking whether `cuda_support` is `True` until we are within the CUDA case. This behaves the same while simplifying the code a bit.

Move `cuda_support` check into CUDA case

---

tests/test_libs_utils.py
ucp/_libs/utils.pxd
ucp/_libs/utils.pyx
ucp/core.py
ucp/endpoint_reuse.py

Makes a few adjustments to `get_buffer_nbytes` signature. Namely replaces `check_min_size` with `min_size`, which is now typed as `Py_ssize_t`. If `min_size` is not positive definite, this is the same as skipping the checking. Also provides some reasonable default values to `min_size` and `cuda_support`.

Simplify `get_buffer_nbytes` `min_size` check

---

ucp/_libs/utils.pxd
ucp/_libs/utils.pyx

This provides the function `get_itemsize` to fast path identification of the `itemsize` some common `typestr`s. Anything else that cannot be easily identified is passed off to NumPy for determination.
Before:
```python
In [1]: import cupy
...: import numpy
...: 
...: from ucp._libs.utils import get_buffer_nbytes
In [2]: s = (10, 11, 12, 13)
...: a_g = cupy.arange(numpy.prod(s)).reshape(s)
In [3]: %timeit get_buffer_nbytes(a_g, check_min_size=None, cuda_support=True)
1.28 µs ± 9.6 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)
```
After:
```python
In [1]: import cupy
...: import numpy
...: 
...: from ucp._libs.utils import get_buffer_nbytes
In [2]: s = (10, 11, 12, 13)
...: a_g = cupy.arange(numpy.prod(s)).reshape(s)
In [3]: %timeit get_buffer_nbytes(a_g, check_min_size=None, …
```

Implement `get_itemsize`

---

ucp/_libs/ucx_api.pyx

Types variables in `assert_ucs_status` so that Cython can use more specific Python C API operations related to those objects (namely `str`s). Also use an [f-string]( https://docs.python.org/3.8/reference/lexical_analysis.html#formatted-string-literals ) to clarify message formatting.

Type variables in `assert_ucs_status`

---

ucp/_libs/ucx_api.pyx

Types variables in `_read_ucx_config` so that Cython can use more specific Python C API operations related to those objects (namely `str`s). Also uses f-strings to clarify message formatting.

Type variables in `_read_ucx_config`

---

ucp/_libs/ucx_api.pyx

This adds more types throughout Cython code. Should help Cython pick more targeted Python C API calls related to Python typed variables. Also should allow for straight C code on C typed variables.

Type more variables in Cython

---

ucp/_libs/ucx_api.pyx

* Drop unneeded parentheses from `if` statement
* Type `line`, which was not typed before
* Type `k` and `v`, which were not typed before
* Handle an error from `fflush` if raised
* Simplify slicing of `k`
* Handle an error from `fclose` if raised

Cleanup `ucx_config_to_dict`

---

ucp/_libs/ucx_api.pyx

* Drop unneeded parentheses from `if` statement
* Handle an error from `fflush` if raised
* Handle an error from `fclose` if raised

Cleanup `UCXEndpoint.info`

---

ucp/_libs/ucx_api.pyx

Fill in the return types of a few `cdef` functions that were missing before.

Specify `cdef` return types

---

ucp/_libs/ucx_api.pyx

As we are responsible for cleaning up the `config` object when we are done with it, make sure that we clean it up ourselves when an exception occurs as no one else will have the opportunity to do so then.

Release `config` on error

---

ucp/_libs/ucx_api.pyx

* Type `cb_args` and `cb_kwargs` as `tuple` and `dict` respectively
* Type `name` as `str`
* Fix `port` typing to `uint16_t` as UCX and hwloc type it
* Use `None` for default arguments

Type `send`, `recv` arguments and `port`

---

ucp/_libs/ucx_api.pyx

Make sure Cython treats `info` as a `dict` when it is used. Also type some frequently used content from `info`. This should help Cython leverage more efficient Python C APIs with these objects.

Type `UCXRequest` `info` as `dict` when used

---

ucp/_libs/ucx_api.pyx

As this is a request counter, we won't use the negative values anyways. So go ahead and type this as `unsigned`. This gives us a bit larger range to work with as well.

Type request count as `unsigned`

---

ucp/_libs/topological_distance.pxd
ucp/_libs/topological_distance.pyx

Make sure `cuda_device_index` matches the expected type of `unsigned int`.

Type `cuda_device_index` as `unsigned int`

---

ucp/_libs/ucx_api.pyx
ucp/core.py
ucp/endpoint_reuse.py

Fixes https://github.com/rapidsai/ucx-py/issues/604
This moves the CUDA and contiguous checks of `Array`s into Cython. Also allows C or F contiguous arrays. Drops the `nbytes` check in Python.

Update Array checks

---

ucp/_libs/ucx_api.pyx

As other UID variables are `unsigned`, make sure this one is `unsigned` as well.
xref: https://github.com/rapidsai/ucx-py/pull/618

Make `ucx_py_request`'s `uid` `unsigned`

---

ucp/_libs/ucx_api.pyx

Instead of using Python properties in Cython, directly access C level properties. This should cutdown on the overhead of these attribute access calls. Particularly in parts of the code that may be more sensitive to them. Also provide access to C implementations of a few methods, these are comparable to `virtual` methods in C++. Finally cleanup the generation of a remaining error message so that the message is only built if the error occurs. Thus bypassing construction of this message when no error happens.

Use C attributes, methods, & minor error message cleanup

---

benchmarks/local-send-recv.py
docs/source/quickstart.rst
tests/test_send_recv.py

Remove remaining usage of `nbytes`. It has been removed in #605 and was the cause of issues in #630 .

Remove remaining `nbytes` references in send/recv calls

---

tests/test_custom_send_recv.py

Removing unused functions and imports in `test_custom_send_recv.py`, which fixes a deprecation warning #621

Clean up of custom send/recv test, which fixes #621

---

ucp/_libs/ucx_api.pyx

Otherwise Cython tries to convert the `size_t` variable to a Python object, which is a bit laborious. This bypasses that.

Cast `req_info["expected_receive"]` as `size_t`

---

ucp/utils.py

This is being removed from cuDF in https://github.com/rapidsai/cudf/pull/6413, we should use its own new `nvtx` package available from `conda-forge`.

Use new NVTX module

---

ucp/_libs/ucx_api.pyx
ucp/_libs/ucx_api_dep.pxd

Fixes a few issues that were causing compilation warnings. First fix typing of `ucp_listener_h` to be a pointer otherwise Cython will ignore later pointer casts, which results in C code that warns about not casting. Second fixes the typing of `ucp_listener_h`, the type of `ucp_err_handler_cb_t` wasn't correctly declared as a function pointer, which caused some unexpected C warnings about unassigned variables. This fixes that typing, which fixes the C warnings as well. Third note that `_get_error_callback` could raise Python exceptions as it works with Python objects (though this is exceedingly unlikely).

Fix compile warnings

---

tests/test_disconnect.py

Fixes https://github.com/rapidsai/ucx-py/issues/643
Try to provide some more context about why this disconnect test may generate errors and what it is actually testing. Namely that the processes exit cleanly.
cc @madsbk @pentschev

Clarify disconnect test

---

tests/test_rma.py
ucp/_libs/ucx_api.pyx
ucp/_libs/ucx_api_dep.pxd
ucp/comm.py
ucp/core.py

First patch to upstream #551 in smaller chunks with a cleaned up API. This brings in all the foundational APIs for RMA short of the changes to end point creation, which a topic I expect to be more controversial than the pure addition changes and get some testing to make sure it doesn't break anything.
In this patch it exposes:
- ucp_worker_fence as ucp.fence()
- ucp_worker_flush_nb as ucp.flush()
- ucp_ep_flush_nb as ep.flush()
- ucp_worker_get_address() as ucp.get_worker_address()
- ucp_worker_release_address() as a destructor in the UCXAddress object
With thanks to @jglaser for bug fixing.

Add fence/flush/worker address APIs

---

docs/source/configuration.rst
ucp/__init__.py

These raise lots of warnings and only benefit the CUDA with TCP-only case, which is not very common right now. If this becomes necessary, we should consider adding them directly into the application, such as dask-cuda when both NVLink and IB are disabled.

Remove default values for UCX_TCP_{TX,RX}_SEG_SIZE

---

README.md

The suggested configuration doesn't really work for intra-node communication, only inter-node communications are possible, since it uses CUDA_IPC.
```
$ UCX_TLS=sockcm,cuda_copy,cuda_ipc ucx_info -eptw -u tra -D net
[1605294229.512128] [r-vmb-ppc-jenkins:12834:0]    ucp_context.c:1108 UCX  ERROR no usable transports/devices (asked sockcm,cuda_copy,cuda_ipc on all devices)
<Failed to create UCP context>
```
User has to specify `ib` to `UCX_TLS` environment variable to use Infiniband

DOC: Fix UCX_TLS environment variable for Infiniband

---

MANIFEST.in
setup.cfg
setup.py

Uses the newer `license_files` key that Python tooling generally respects to package the license file more simply. Drops other ways of handling the license file to simplify things.

Simplify license file packaging

---

ci/gpu/build.sh

Auto-merge triggered by push to `branch-0.17` that creates a PR to keep `branch-0.18` up-to-date. If this PR is unable to be immediately merged due to conflicts, it will remain open for the team to manually merge.

[gpuCI] Auto-merge branch-0.17 to branch-0.18 [skip ci]

---

ci/checks/style.sh
ci/cpu/build.sh
ci/gpu/build.sh
ci/local/README.md

In CI folder the following changes have been made:
- Remove logger function and replace all logger calls with gpuci_logger
- Removed all ellipses ... from logger messages
- Prepend /opt to the conda path in PATH variable
- Replace conda with gpuci_conda_retry for build and install calls  (Did not replace conda activate with gpuci_conda_retry) 
- Replace source activate <env> with the following:
. /opt/conda/etc/profile.d/conda.sh
conda activate rapids
- Replace conda list with more verbose information:
conda info
conda config --show-sources
conda list --show-channel-urls
- Update Copyright year in the top of scripts to include 2020 if applicable
- Set PARALLEL_LEVEL to ${PARALLEL_LEVEL:-4}
- Set gpuci_conda_retry flags in cpu/build.sh
Setup 'gpuci_conda_retry' for build retries (results …

Gpuciscripts clean and update

---

ucp/_libs/ucx_api.pyx

This is at least one of the causes for unclean endpoint closure.

Ensure `ucp_ep_close_nb` is awaited for

---

ucp/utils.py

This fixes test warnings such as:
```python
Task was destroyed but it is pending!
task: <Task pending name='Task-31' coro=<BlockingMode._arm_worker() running at ucp/continuous_ucx_progress.py:88>>
```

Prevent closing event_loop too early

---

ucp/_libs/ucx_api.pyx

This resolves errors such as below:
```python
asyncio:base_events.py:1707 Task exception was never retrieved
future: <Task finished name='Task-102' coro=<_listener_handler_coroutine() done, defined at /gpfs/fs1/pentschev/miniconda3/envs/ucx-master-110-0.18.210127/lib/python3.8/site-packages/ucp/core.py:148> exception=UnicodeDecodeError('utf-8', b'#\n# UCP endpoint\n#\n#               peer: <no debug data>\n#                 lane[0]: 255:\xc0\x7f/.0 md[60]                   -> md[255]/posix   \n#                 lane[1]:  0:tcp/enp1s0f0.0 md[0]          -> md[0]/tcp      am am_bw#0 wireup\n#                 lane[2]:  1:cuda_copy/cuda.0 md[1]        -> md[1]/cuda_cpy rma_bw#0\n#\n#                tag_send: 0..<egr/short>..8185..<egr/zcopy>..8192..<rndv>..(inf)\n#            tag_send_nbr: …
```

Fix character decoding

---

docs/source/install.rst

Note that the "Edit on GitHub" links on https://ucx-py.readthedocs.io point to https://github.com/quasiben/ucx-py/tree/fix-rtd, so I don't know if these changes will get automatically applied.

Update install instructions for new UCX version

---

docs/source/install.rst

Auto-merge triggered by push to `branch-0.18` that creates a PR to keep `branch-0.19` up-to-date. If this PR is unable to be immediately merged due to conflicts, it will remain open for the team to manually merge.

[gpuCI] Auto-merge branch-0.18 to branch-0.19 [skip ci]

---

ci/gpu/build.sh

These recently dropped the `master` branch and switched to `main`. So update the install steps to use `main` instead.

Install Dask + Distributed from `main`

---

ucp/_libs/ucx_api_dep.pxd
ucp/core.py
ucp/endpoint_reuse.py

Now using a `dict` for the endpoint tags.
This PR is part **1** of an effort to merge https://github.com/rapidsai/ucx-py/pull/648 in a divide-and-conquer approach.

Clean up send/recv tags

---

ucp/_libs/src/c_util.c
ucp/_libs/src/c_util.h
ucp/_libs/tests/test_listener.py
ucp/_libs/ucx_api.pyx
ucp/_libs/ucx_api_dep.pxd
ucp/core.py

This will allow us to pass the responsibility of assigning a listener port to UCX when one isn't specified by the user, rather than doing so in UCX-Py.

Support `ucp_listener_query` to find listener's IP/port

---

tests/test_multiple_nodes.py

Creating too many connections simultaneously may cause UCX to hang due to the SOMAXCONN limit. This PR resolves that issue in `test_multiple_nodes`.

Respect somaxconn in test_multiple_nodes

---

tests/test_rma.py
tests/test_send_recv.py
tests/test_shutdown.py

Fixes test file that could cause warnings such as:
```python
Task was destroyed but it is pending!
task: <Task pending name='Task-31' coro=<BlockingMode._arm_worker() running at ucp/continuous_ucx_progress.py:88>>
```
Fixes also some deprecation warnings on using `pytest.yield_fixture`.

Fix early closing of event_loop in test_shutdown

---

ci/gpu/build.sh

This should unblock CI timeouts trying to resolve conda environment.

Remove Distributed's PyTorch serialization test from CI

---

setup.py
tests/test_send_recv_am.py
ucp/_libs/ucx_api.pyx
ucp/_libs/ucx_api_dep.pxd
ucp/comm.py
ucp/core.py

This PR adds initial support for the Active Message UCX API. There are currently some limitations:
- Receiving rendezvous messages is not supported yet;
- Only host messages are supported.
The limitations above are intended to avoid this PR getting even longer and will be addressed in a follow-up PR.

Add support for UCX AM (Active Messages)

---

ucp/_libs/tests/test_mem.py
ucp/_libs/ucx_api.pyx
ucp/_libs/ucx_api_dep.pxd

Filling out more of the low level UCX API. This one covers the mapping of existing memory/allocation of new memory registered to a UCX context and packing an Rkey that will, after a future PR adds RMA/AMO operations, allow for one sided operations against this memory.

Memory allocation/registration and rkey management

---

ucp/_libs/ucx_memory_handle.pyx
ucp/_libs/ucx_rkey.pyx

Fixes a couple of build warnings:
```cpp
ucp/_libs/ucx_api.c: In function ‘__pyx_pf_3ucp_5_libs_7ucx_api_18_ucx_mem_handle_finalizer’:
ucp/_libs/ucx_api.c:16449:18: warning: assignment makes pointer from integer without a cast [-Wint-conversion]
__pyx_v_handle = __pyx_v_handle_as_int;
^
ucp/_libs/ucx_api.c: In function ‘__pyx_pf_3ucp_5_libs_7ucx_api_22_ucx_remote_mem_finalizer_post_flush’:
ucp/_libs/ucx_api.c:20611:23: warning: assignment makes pointer from integer without a cast [-Wint-conversion]
__pyx_v_rkey_handle = ((uintptr_t)__pyx_v_rkey->_handle);
^
```

Fix "assignment makes pointer from integer without a cast" warnings

---

ucp/_libs/packed_remote_key.pyx

This one was fun to track down. Small fix so that the `from_mem_handle` function path returns the correct object, instead of returning a new copy with a 'use after free' bug.

Fix use after free bug in PackedRemoteKey

---

ucp/_libs/utils.pyx

While working on the RMA branch I ran into this interesting behavior. As it stands now the `assert_ucs_status()` function will treat `UCS_INPROGRESS` as an error and raise an exception. I looked through the code and don't see how this change would affect anything outside of the RMA implicit interface, but I wanted to break this change out into it's own one liner to see if any tests have a problem with this change

Handling UCS_INPROGRESS in assert_ucs_status()

---

.github/workflows/rtd.yml

Forgot you need to set a Git username and email in order to make the commit and push it; this should fix build failures.

Fix RTD workflow

---

conda/environments/builddocs_py37.yml
readthedocs.yml

After retargetting the repo/branch for the Read the Docs builds, I noticed that builds pass when using the standard version of UCX:
- https://readthedocs.org/projects/ucx-py/builds/13648990/
However, this build depends on a Conda installed version of UCX-Py, specifically disabling the `setup.py` install of the package:
https://github.com/rapidsai/ucx-py/blob/8a597a56882107ce6ef6c0574a36a1d36626f525/readthedocs.yml#L4-L6
This means that the API reference will be out of date, and also [breaks builds](https://readthedocs.org/projects/ucx-py/builds/13648544/) triggered by the [`readthedocs`](https://github.com/rapidsai/ucx-py/tree/readthedocs) branch, which does not have UCX-Py listed in its docs environment. This PR enables this install, and removes the package from the Conda environment.
If …

Use `setup.py` installed ucx-py in docs build

---

ucp/_libs/tests/test_server_client_am.py

This PR fixes an issue when asserting the wireup message and NumPy is used as a host allocator, as `numpy.ndarray` can't be directly compared to `bytearray`.

Fix wireup assertion in AM core test

---

.gitignore
setup.py

It looks like Cython is required to build from source, so the setup should just fail immediately if it can't be imported.

Remove try/except block for Cython import in `setup.py`

---

tests/test_multiple_nodes.py
tests/test_send_recv.py
tests/test_send_recv_am.py
tests/test_send_recv_two_workers.py
tests/test_tags.py
tests/test_ucx_getters.py

This is a preparation for endpoint error handling. UCX-Py currently try as best as possible to ensure endpoints are closed according to each object's lifetime. However, this can't always be ensured given the async behavior in `ucp.core`. For example, a `ucp.core.Endpoint` object does not call `abort` or `close`, specifically `close` would be desired to inform the other end that it is closing. Because that is an async function, we can't rely on it for a destructor. It's ensured that the underlying synchronous `ucp._libs.UCXEndpoint` object is destroyed when its weakref count goes to zero, and `ucp_ep_close_nb` is called. With the endpoint error handling work in https://github.com/rapidsai/ucx-py/pull/693 , we will be switching to `UCP_EP_CLOSE_MODE_FORCE` that doesn't guarantee inflight …

Close endpoints in ucp.core tests

---

ucp/_libs/ucx_api_dep.pxd
ucp/_libs/ucx_worker.pyx

The changes here resolve the issue that causes warnings to be raised at process termination, such as below:
```
[1621606990.204443] [dgx14:77681:0]       tag_match.c:61   UCX  WARN  unexpected tag-receive descriptor 0x55c9b1ff2fc0 was not matched
```
The reason for that was the we weren't draining the UCX worker during shutdown, where some messages may have gone uncatched, such as shutdown messages.

Drain tag messages on worker finalizer

---

ci/gpu/build.sh

Forward-merge triggered by push to `branch-0.20` that creates a PR to keep `branch-0.21` up-to-date. If this PR is unable to be immediately merged due to conflicts, it will remain open for the team to manually merge.

[gpuCI] Forward-merge branch-0.20 to branch-0.21 [skip ci]

---

ci/gpu/build.sh

This is done as a workaround for https://github.com/dask/distributed/issues/4902 and unblock CI. It may be reverted should the resolution be that Distributed will ship `conftest.py` with release packages.

Clone Distributed repository and run tests from clone

---

ucp/_libs/ucxio.pyx

While making this class I found out that I could remove an ep parameter after I found out it was in rkey and I could use that instead of passing it in. It wasn't removed from the docs though. Fix the docs so that users won't be confused.

Fix bad documentation in UCXIO

---

.pre-commit-config.yaml
ci/checks/style.sh

With rapidsai/integration#286, the version of `isort` running on gpuCI will be bumped to 5.6.4, allowing us to enforce the sorting of packages in Cython (pyx, pxd) files. This PR intends to:
- Enable these checks in the gpuCI style script
- Enable Cython package resorting in the pre-commit hook
- Resort all the Cython files in this repo so they pass the newly enabled checks

Bump isort, enable Cython package resorting

---

benchmarks/send-recv-core.py
benchmarks/send-recv.py
debug-tests/debug_utils.py

Resolves deprecation warnings such as the one below:
```python
FutureWarning: parse_bytes is deprecated and will be removed in a future release. Please use dask.utils.parse_bytes instead.
from distributed.utils import parse_bytes
```

Update parse_bytes imports to resolve deprecation warnings

---

debug-tests/client.py
tests/test_custom_send_recv.py
tests/test_send_recv_two_workers.py

Recently there has been a change of location of where the testing utils of cudf reside. This PR is adapting to those changes.

Fix `assert_eq` related imports

---

docs/source/configuration.rst
docs/source/dask.rst
docs/source/ucx-debug.rst

The `sockcm` transport was removed in UCX 1.10, this change updates documentation to clarify the correct way of using it for UCX < 1.9 and >= 1.10.

Update documentation on `sockcm` usage

---

ci/gpu/build.sh

Additionally remove duplicate distributed tests covering UCX-Py.

Fix typo in CI script that sets wrong UCX_TLS for UCX 1.11

---

ci/gpu/build.sh
ucp/utils.py

If `UCXPY_IFNAME` is undefined, let `ucp.get_address` try to pick a suitable interface to establish connections. This is helpful to allow CI testing on different systems without knowing what interfaces are available to establish connection between two UCX processes.

Try different interfaces if UCXPY_IFNAME is undefined

---

ucp/_libs/tests/test_mem.py
ucp/_libs/tests/test_peer_send_recv.py
ucp/_libs/tests/test_rma.py
ucp/_libs/utils_test.py

On newer UCX versions it's important to have endpoint error handling enabled, this ensures that core tests will enable it depending on the UCX version installed.

Change core tests default endpoint error handling according to UCX version

---

tests/test_disconnect.py
tests/test_shutdown.py

Endpoint error handling shall always be enabled on UCX 1.10 and above, this removes disconnect/shutdown testing of UCX 1.10+ when endpoint error handling is disabled.

Drop disconnect/shutdown tests without error handling in UCX >= 1.10

---

tests/test_shutdown.py
ucp/_libs/transfer_am.pyx
ucp/_libs/ucx_endpoint.pyx

Cancelling `am_recv` was only done when an error occurred during AM message receive callback in the worker, but if an endpoint closed while the client is waiting for that message it would hang indefinitely. This change cancels any waiting `am_recv` at the endpoint finalizer as well.

Cancel waiting `am_recv` if endpoint closes

---

ucp/_libs/ucx_address.pyx

According to the UCX documentation, the [worker address cannot be used after `ucp_worker_release_address`](https://openucx.github.io/ucx/api/v1.11/html/group___u_c_p___w_o_r_k_e_r.html#ga94260829739496267d2c8d86414b863d). This change fixes that by adding a finalizer to `UCXAddress` that will only release the handle when the object is destroyed.
Even though `test_peer_communication` passed, the errors would be printed to stdout, which this change resolves as well.
```python
Traceback (most recent call last):
File "/datasets/pentschev/miniconda3/envs/gdf/lib/python3.8/site-packages/ucp/exceptions.py", line 13, in log_errors
yield
File "ucp/_libs/transfer_common.pyx", line 55, in ucp._libs.ucx_api._send_callback
cb_func(req, exception, *cb_args, **cb_kwargs)
File "ucp/_libs/ucx_rkey.pyx", …
```

Fix UCXAddress finalizer

---

ucp/_libs/ucx_endpoint.pyx

Without this check the previous condition would fail in the event that AM is not enabled with errors such as below:
```python
Traceback (most recent call last):
File "/datasets/pentschev/miniconda3/envs/gdf/lib/python3.8/weakref.py", line 642, in _exitfunc
f()
File "/datasets/pentschev/miniconda3/envs/gdf/lib/python3.8/weakref.py", line 566, in __call__
Exception ignored in: <finalize object at 0x7f37c01f1480; dead>
Traceback (most recent call last):
File "/datasets/pentschev/miniconda3/envs/gdf/lib/python3.8/weakref.py", line 566, in __call__
return info.func(*info.args, **(info.kwargs or {}))
File "ucp/_libs/ucx_object.pyx", line 16, in ucp._libs.ucx_api._handle_finalizer_wrapper
File "ucp/_libs/ucx_endpoint.pyx", line 88, in ucp._libs.ucx_api._ucx_endpoint_finalizer
TypeError: …
```

Add missing check for enabled AM in endpoint finalizer

---

tests/test_from_worker_address.py
ucp/comm.py
ucp/core.py

Using a UCX listener may not be possible for systems that are IP-less, as that is required to create an endpoint to the listening server. For such cases, it's possible to use the UCX worker address to connect to a remote worker. This PR exposes the worker address feature to the UCX-Py async API, additionally includes a couple of tests that can be used as reference for setting up a "server" worker that exposes its address and handle client connections in a similar way to how the UCX-Py listener does.

Add support for endpoints from worker address on async API

---

docs/source/install.rst
setup.py

For UCX 1.9 and older we needed hwloc to determine the closest InfiniBand device to a GPU. With UCX 1.10+ this isn't necessary anymore, so it's a deprecated feature. Since building with hwloc can be problematic for some use cases, add a new compile-time environment variable to allow disabling build of topological distance code.

Add compile-time variable UCXPY_DISABLE_HWLOC

---

docker/Dockerfile
docker/README.md
docker/run.sh

To help users get started with UCX-Py, add a reference Docker container. The container is based off of the official `python:3` container, we then install dependencies required to build and use UCX and UCX-Py via `apt`. When running, the container will install Python dependencies required by UCX-Py, build UCX from source, build UCX-Py and run tests and benchmarks. Currently includes a minimal setup only, without CUDA, MOFED or rdma-core support.

Add reference Docker container

---

docs/source/install.rst

Consistently instructs users to use `pip install -v .` to install ucx-py, to remove any ambiguity from the instructions on disabling building with hwloc support.

Make ucx-py installation blocks consistent

---

tests/test_endpoint.py
tests/test_topological_distance.py
ucp/_libs/tests/test_config.py
ucp/_libs/tests/test_endpoint.py

Config tests for UCX 1.12 with the async API were already fixed in https://github.com/rapidsai/ucx-py/pull/804, but the core tests missed the same fixes.
Additionally, skip `TopologicalDistance` tests when UCX-Py is built using `UCXPY_DISABLE_HWLOC=1`, as well as skipping endpoint close callback tests for UCX < 1.11.

Fix core config tests for UCX 1.12

---

ucp/__init__.py

UCX_MEMTYPE_CACHE=n is still required even for UCX 1.12 (see
https://github.com/openucx/ucx/issues/7575), so we reenable it.
Reordering the import is also required to prevent UCS warnings when
Cython code is imported.

Reorder and reenable UCX_MEMTYPE_CACHE=n for all UCX versions

---

ci/gpu/build.sh
ci/release/update-version.sh

This PR updates the `RAPIDS_VERSION` variable and also includes a command in `update-version.sh` to ensure that it gets updated during releases.

Update `RAPIDS_VERSION` var and `update-version.sh` script

---

tests/test_from_worker_address_error.py
ucp/_libs/ucx_endpoint.pyx
ucp/_libs/ucx_worker.pyx
ucp/core.py

When am_recv is being awaited and an endpoint error, the future needs to be canceled to prevent an indefinite hang.

Ensure am_recv waiting futures are canceled

---

tests/test_endpoint.py
ucp/_libs/tests/test_cancel.py
ucp/_libs/ucx_endpoint.pyx
ucp/_libs/ucx_worker.pyx

This is important because UCX may reuse the same endpoint handle, and if a message is canceled during then endpoint finalizer, a message received on the same (new) endpoint handle may be canceled incorrectly.
Due to this, `test_close_after_n_recv[am]` would fail non-deterministically.

Prevent endpoint canceling AM messages multiple times

---

tests/test_endpoint.py
tests/test_probe.py
ucp/_libs/tests/test_probe.py
ucp/_libs/ucx_endpoint.pyx
ucp/core.py

When receiving with the AM API, it may happen that a remote endpoint has closed but messages were delivered to the local worker. By allowing to probe that worker for messages, it's possible to consume those instead of discarding them. Only after the remote endpoint has closed and no more messages exist on the local worker a `UCXCloseError` is raised.

Probe AM messages before raising UCXCloseError

---

docs/source/install.rst
ucp/__init__.py

Besides stability, UCX 1.11.1 includes important features such as:
* Automatic InfiniBand<->CUDA device mapping without specifying `UCX_NET_DEVICES` explicitly;
* InfiniBand allocation registration cache without patching source;
* Endpoint error handling with CUDA IPC;
* etc.
All features above will simplify usage both with and without Dask and RAPIDS. Therefore, we would like to deprecate older versions of UCX, to be removed at a later release.

Add FutureWarning of UCX < 1.11.1 deprecation

---

ci/release/update-version.sh

I recently added a `sed` command (#811) to update the `RAPIDS_VERSION` in `ci/gpu/build.sh`. However, I now realize that the `NEXT_MAJOR` and `NEXT_MINOR` variables that I used correspond to the `ucx-py` versions (i.e. `0.22`) and not the RAPIDS versions (i.e. `22.12`). Therefore my changes would result in an incorrect string replacement.
I've commented out the line instead of removing it because we have some `update-version.sh` script improvements that are coming that will allow us to update both RAPIDS and `ucx-py` versions throughout the repositories.

Revert `update-version.sh` changes

---

ucp/__init__.py

This is necessary to maintain good performance on GPUs with large BAR1 size (greater or equal to the total GPU memory size). Starting with UCX 1.12 this value is set to 0.1 by default to ensure registration doesn't fail with GPUs that have a BAR1 size lower than the total GPU memory size (e.g., T4).
Currently we're setting to 1.0 when all GPUs have a large BAR1, in the future it may be useful to compute the real BAR1/TotalGPUMemory ratio to set this number. This is also a global setting, for fine-grained settings the application should take care of changing this value appropriately as UCX-Py doesn't know which GPUs are going to be used by the application at import time.
Additionally, setup logger before environment variables are set and log what's being set.

Set UCX_CUDA_COPY_MAX_REG_RATIO=1.0 when GPUs permit

---

tests/test_from_worker_address_error.py

Only TAG messages were covered by the xfail condition in `test_from_worker_address_error`, but AM should also xfail on UCX 1.11.

xfail AM `test_from_worker_address_error` on UCX 1.11

---

docs/source/configuration.rst
ucp/__init__.py

Add `UCX_MAX_RNDV_RAILS=1` to prevent crashes in UCX 1.12.0 caused by recent changes, more specifically when `UCX_CUDA_COPY_MAX_REG_RATIO=1.0` to maintain better performance on GPUs with large BAR1.
Add new subsection on UCX-Py default environment variables and further improve UCX-Py configuration docs.

Set `UCX_MAX_RNDV_RAILS=1` on UCX >= 1.12.0 and update configurations docs

---

ucp/__init__.py

Should address gpuCI errors on build instances that don't contain GPUs, as well as any other users who don't have GPUs installed.

Skip BAR1 check on NVML error

---

ci/gpu/build.sh

Distributed tests are now tested by gpuCI in the Distributed repo itself, and recent changes to gpuCI now make install Distributed from conda packages that do not include `distributed.comm.tests`.

Remove Distributed tests from CI

---

docker/README.md
docker/UCXPy-CUDA.dockerfile
docker/bench-all.sh

Add a "full-fat" dockerfile that provisions a container with sufficient bits and pieces that UCX builds with IB and NVLink support.
Running the container and exposing sufficient devices from the host OS is non-trivial so update instructions for usage with an example scenario on a DGX-1.

Dockerfile with Infiniband/NVLink capabilities

---

setup.cfg
tests/test_config.py
ucp/core.py

In the config dict, UCX variables are not prefixed with UCX_, so we must
take that into account when comparing to the environment.
While we're here, take a copy of the user-provided config dict so that
we don't modify it behind their back.

Fix environment override logic in ucp.init

---

conda/recipes/ucx-py/meta.yaml

`GIT_DESCRIBE_HASH` already has a `g` prefix in it. So there is no need to add one ourselves.

Drop `g` prefix in Conda recipe build string

---

docker/README.md
docker/UCXPy-MOFED.dockerfile
docker/UCXPy-rdma-core.dockerfile
docker/build-ucx-py.sh
docker/build-ucx.sh
docker/ucx-py-cuda11.5.yml

Rather than relying on exact matching MOFED versions, use rdma-core
which is forward-compatible with MOFED version >= 5.x.
To facilitate downstream users adopting the build setup, split the
building and installing of UCX and UCX-Py into scripted steps for which
the conda environment name and UCX version to use can be configured.
Adapt the existing MOFED-based docker file to use this setup too.
Closes #846.

Add dockerfile using librdmacm to provide infiniband interfaces

---

ci/cpu/build.sh

Looks like with #843 we removed the version suffix from the published nightly packages - this PR adds this back in.

Add `VERSION_SUFFIX` to nightly packages

---

ucp/_libs/ucx_context.pyx

The UCX_TLS environment variable allows one to specify either:
- specific transports to enable (e.g. UCX_TLS=rc,tcp,cuda);
- specific transports to disable (via a negation flag at the front of
the list). For example UCX_TLS=^cma,xpmem means all \ {cma, xpmem}.
To correctly determine whether the UCX context has cuda support we
need to handle both of these cases. Closes #856.

Handle negation (^) when determining cuda_support from UCX_TLS

---

docker/README.md
docker/UCXPy-MOFED.dockerfile
docker/UCXPy-rdma-core.dockerfile
docker/build-ucx-py.sh
docker/build-ucx.sh

This significantly speeds up building images, and makes installing
packages in the image much more pleasant, since the solver is so much
faster.
This is low-priority, but a reasonable quality of life improvement when building the containers regularly.

Use mamba rather than conda in docker files

---

docker/README.md
docker/UCXPy-MOFED.dockerfile
docker/UCXPy-rdma-core.dockerfile
docker/build-ucx-py.sh
docker/build-ucx.sh

Forward-merge triggered by push to `branch-0.26` that creates a PR to keep `branch-0.27` up-to-date. If this PR is unable to be immediately merged due to conflicts, it will remain open for the team to manually merge.

[gpuCI] Forward-merge branch-0.26 to branch-0.27 [skip gpuci]

---

benchmarks/send-recv.py
debug-tests/client.py
debug-tests/server.py
debug-tests/test_endpoint_error_callback.py
debug-tests/test_send_recv_many_workers.py
tests/test_disconnect.py
tests/test_from_worker_address.py
tests/test_from_worker_address_error.py
tests/test_multiple_nodes.py
tests/test_send_recv_two_workers.py
ucp/comm.py
ucp/core.py
ucp/utils.py

Since `asyncio.get_event_loop()` is deprecated starting on Python 3.10 and will eventually become an alias to `asyncio.get_running_loop()`, implement a new function to emulate the old behavior to be used where appropriate.
In https://github.com/dask/distributed/pull/6231, some of the fixtures were updated to match `asyncio`'s updates, which also caused some problems with the event loop being created in `ucp.ApplicationContext`, which can be seen in [this log](https://raw.githack.com/pentschev/ucx-py-ci/test-results/assets/ucx-master-dask-cuda-202207052200.html#0161d81a-ac60-4f1b-87ac-9b4bde5931e5) of nightly runs on a DGX-1, this fixes that.

Add `get_event_loop()` util function

---

benchmarks/cudf-merge.py
ucp/_libs/utils.py
ucp/utils.py

This adds several bugfixes and improvements:
- Correctly assign `CUDA_VISIBLE_DEVICES`;
- Create CUDA contexts before initializing UCX;
- Ensure merge uses the `"key"` column and asserts expected result size;
- Allow running the benchmark for multiple iterations;
- Allow running multiple warmup iterations;
- Prints results for each iteration;
- Allow enabling garbage collection after each itearation.

Update cuDF merge benchmark

---

ucp/benchmarks/backends/__init__.py

With the reorganization in https://github.com/rapidsai/ucx-py/pull/873 , `ucp/benchmark/backends/__init__.py` was missing causing non-dev UCX-Py installs to fail when attempting to run `send_recv` benchmarks, this change adds the missing file.

Add missing `__init__.py` and copyright

---

ucp/benchmarks/send_recv.py

We need to ensure the value we read is converted to int.

Correctly parse bytes argument when dask unavailable

---

docs/source/install.rst

This flag isn't necessary, as `--with-cuda` will take are of setting correct flags.

Remove redundant CPPFLAGS from UCX install docs

---

.github/ops-bot.yaml

This file will enable ops-bot to perform the "copy_prs" action, described here: https://github.com/rapidsai/ops-bot/#plugins
It will help run GitHub Actions using rapidsai self-hosted runners from pull requests (needed for the wheel project).

Enable copy_prs behavior of ops-bot

---

docker/bench-all.sh
docker/run.sh

With recent changes from https://github.com/rapidsai/ucx-py/pull/873, launching benchmarks has been changed. Docker scripts must be adjusted accordingly.

Update Docker scripts to reflect recent benchmark changes

---

ucp/_libs/ucx_endpoint.pyx
ucp/_libs/utils.pyx

A crash was reported after `tmpfile` in `create_text_fd()` raised an exception, causing a segmentation fault. This was due to the missing `except *` Cython handle for that function. The `_err_cb` also used `except *` handle which is unnecessary, that is now removed.

Fix Cython exceptions

---

setup.py

`tests_require` was deprecated by setuptools over three years ago now. `extras_require["test"]` is the standard replacement.

Replace tests_require with extras_require.

---

pyproject.toml

This file is required for using newer PEP517-compliant projects.

Add pyproject.toml file.

---

conda/environments/builddocs.yml
conda/recipes/ucx-py/meta.yaml
docker/ucx-py-cuda11.5.yml
docs/source/install.rst
setup.py

In the past `psutil` was used to generate a random port number for the listener, but this is not anymore used as now UCX's random port generation is utilized, but the dependency to `psutil` was not removed. This PR removes the not anymore used dependency.

Remove `psutil` dependency

---

.github/ops-bot.yaml

This PR enables the auto-merge for `ucx-py`. This means that all future PRs can be merged with the `@gpucibot merge` command.

Enable auto-merger

---

docs/source/install.rst
docs/source/quickstart.rst

Python 3.6 and above _should_ still work, but are not actively tested, thus upgrading to 3.8 which is actually tested should be encouraged.

Upgrade Python version to 3.8 in docs

---

ucp/__init__.py
ucp/_libs/tests/test_cancel.py
ucp/_libs/tests/test_endpoint.py
ucp/_libs/tests/test_probe.py
ucp/_libs/tests/test_server_client.py
ucp/_libs/tests/test_server_client_am.py
ucp/_libs/utils.py
ucp/_libs/utils.pyx
ucp/benchmarks/utils.py

Move `get_address` into `utils.py`, which is a pure-Python function that does not need to live in a Cython source file.
Optionally attempt to query for `docker*` network interface, if other known interfaces fail in a Docker container. If still no valid IP address could be determined, raise an exception with information on how the user can manually setup to proceed.

Move `get_address` and improve compatibility and error handling

---

ci/gpu/build.sh

This PR fixes the `RAPIDS_VERSION` environment variable in `ci/gpu/build.sh` that seems to be breaking CI.
Ordinarily, I'd also update the `update-version.sh` script, but this problematic script will be going away when we migrate `ucx-py` to GitHub Actions, which will be happening before the next release.
Therefore it's fine to just manually edit this string for now.

Fix `RAPIDS_VERSION` environment variable

---

.github/workflows/build.yaml
.github/workflows/test.yaml

This PR updates the workflows to change some of the events used to trigger the `build.yaml` and `test.yaml` workflows.
These changes are necessary due to a recent change in how we call these workflows from the nightly pipeline in the https://github.com/rapidsai/actions.
See https://github.com/rapidsai/actions/pull/7 for more details.

Update GH Action Workflows

---

.github/workflows/build.yaml
.github/workflows/test.yaml

The repo key is no longer needed by the wheel workflow.

Remove unnecessary repo: param for wheels

---

.github/workflows/build.yaml

This PR fixes a typo in #914.
Skipping CI since this file isn't tested in PRs.

Fix `build.yaml` workflow file name [skip gpuci]

---

.github/workflows/build.yaml
.github/workflows/pr.yaml
.github/workflows/test.yaml
conda/recipes/ucx-py/conda_build_config.yaml
conda/recipes/ucx-py/meta.yaml
dependencies.yaml

This PR updates `ucx-py` to build against branch [cuda-118](https://github.com/rapidsai/shared-action-workflows/compare/cuda-118) of the `shared-action-workflow` repository.
That branch contains updates for CUDA `11.8` and Python `3.10` packages.
It also includes some minor file renames.
This PR will unblock the following PRs:
- https://github.com/rapidsai/raft/pull/1120
- https://github.com/rapidsai/dask-cuda/pull/1080

Build CUDA `11.8` and Python `3.10` Packages

---

.github/ops-bot.yaml

This change should've been added in #914.
It enables the _Recently Updated_ check that is intended to be used with our GitHub Actions implementation.
For more details on the check, view the docs page below:
- https://docs.rapids.ai/resources/recently-updated/

Add `recently_updated` check

---

.pre-commit-config.yaml

Forward-merge triggered by push to `branch-0.30` that creates a PR to keep `branch-0.31` up-to-date. If this PR is unable to be immediately merged due to conflicts, it will remain open for the team to manually merge.

Forward-merge branch-0.30 to branch-0.31

---

.github/workflows/build.yaml
.github/workflows/pr.yaml
.github/workflows/test.yaml
ci/release/update-version.sh

This PR updates the `shared-action-workflow` branches to use `branch-23.02`.
It also adds an entry to `update-version.sh` to keep these version strings up-to-date.

Update shared workflow branches & `update-version.sh`

---

conda/recipes/ucx-py/meta.yaml

This PR moves the date string from the version to the build string for conda recipes in this repository.
This is necessary to ensure that the conda packages resulting from PR builds can be installed in the same environment as nightly conda packages, which is useful for testing purposes.
Additionally, this prevents a bug from occurring where the Python builds fail because the date string it computes is different than the one computed by the C++ build, therefore causing the Python build to search for a C++ build artifact that doesn't exist.
xref: https://github.com/rapidsai/rmm/pull/1195

Move date to build string in `conda` recipe

---

pyproject.toml
tests/test_shutdown.py
tests/test_tags.py

We were maintaining support for Python 3.6 due to some users still requiring that, they are still on older UCX-Py releases so they are ok with us updating to Python 3.8+ on newer releases and they will try upgrading to a newer Python release soon.

Update requirement to Python >= 3.8

---

conda/recipes/ucx-py/conda_build_config.yaml

https://github.com/conda-forge/ucx-split-feedstock/pull/111 was merged and UCX v1.14.0 is now available on conda-forge which we should support.

Update UCX pin to allow 1.14

---

.github/workflows/pr.yaml
.github/workflows/test.yaml
ci/release/apply_wheel_modifications.sh

cupy just released version 12, which we do not yet support, so wheels CI must be pinned to require a lower version. We also decided not to overwrite the `__version__` in wheels on other RAPIDS repos, so this PR makes changes to match that.

Pin cupy and unset version

---

.github/workflows/pr.yaml
.github/workflows/test.yaml
ci/release/apply_wheel_modifications.sh

Forward-merge triggered by push to `branch-0.31` that creates a PR to keep `branch-0.32` up-to-date. If this PR is unable to be immediately merged due to conflicts, it will remain open for the team to manually merge.

Forward-merge branch-0.31 to branch-0.32

---

.github/workflows/build.yaml
.github/workflows/pr.yaml
.github/workflows/test.yaml
.readthedocs.yml
dependencies.yaml
docker/ucx-py-cuda11.5.yml
docs/source/install.rst
docs/source/quickstart.rst
pyproject.toml

This PR drops Python 3.8 in favor of 3.9.

Dropping Python 3.8

---

ci/release/update-version.sh
pyproject.toml
ucp/__init__.py

Forward-merge triggered by push to `branch-0.32` that creates a PR to keep `branch-0.33` up-to-date. If this PR is unable to be immediately merged due to conflicts, it will remain open for the team to manually merge.

Forward-merge branch-0.32 to branch-0.33

---

.github/workflows/build.yaml
.github/workflows/pr.yaml
.github/workflows/test.yaml
conda/recipes/ucx-py/meta.yaml
dependencies.yaml

Add CUDA 12.0 build matrix

---

.github/workflows/build.yaml

Nightly tests have been failing for some time because the required variables `package-name` and `package-dir` were not being supplied in the wheel build workflows.
Failures look like:
```
The workflow is not valid. .github/workflows/build.yaml (Line: 58, Col: 11): Input package-name is required, but not provided while calling. .github/workflows/build.yaml (Line: 64, Col: 15): Invalid input, script is not defined in the referenced workflow.
```
https://github.com/rapidsai/ucx-py/actions/runs/5652857349
With the recent changes to workflows, these parameters are no longer required for the build step, but the publish step still needs the `package-name`.

Add package-name to wheel publish step

---

.github/workflows/build.yaml

Forward-merge triggered by push to `branch-0.33` that creates a PR to keep `branch-0.34` up-to-date. If this PR is unable to be immediately merged due to conflicts, it will remain open for the team to manually merge.

Forward-merge branch-0.33 to branch-0.34

---

.github/workflows/build.yaml

Nightly tests failed because an extra `script` variable was passed to the wheel publish workflow.
Failures look like:
```
Invalid workflow file: .github/workflows/build.yaml#L65
The workflow is not valid. .github/workflows/build.yaml (Line: 65, Col: 15): Invalid input, script is not defined in the referenced workflow.
```
https://github.com/rapidsai/ucx-py/actions/runs/5664871243
Follow-up to #973.

Remove script input from publish step in build.yaml.

---

conda/recipes/ucx-py/meta.yaml
dependencies.yaml

This PR is a test to validate that upstream ucx builds are no longer broken, at which point we will also be able to remove this pinning.

Undo manual pinning

---

conda/recipes/ucx-py/meta.yaml

The ucx run requirement should be inferred from the run exports of ucx since it is part of the host requirements. The run explicit requirement was added to fix upstream issues with ucx packaging that have since been fixed. All other patches were removed in https://github.com/rapidsai/ucx-py/pull/987, but this reversion was missed.

Remove ucx from explicit run reqs

---

.github/workflows/build.yaml
.github/workflows/pr.yaml
.github/workflows/test.yaml

This PR builds conda packages using CUDA 12 on ARM.
This work is targeting 23.12. Closes #989.

ucx-py: Build CUDA 12.0 ARM conda packages.

---

ucp/benchmarks/backends/ucp_async.py
ucp/benchmarks/backends/ucp_core.py
ucp/benchmarks/send_recv.py

Some transports (e.g., `sm`) do not support endpoint error handling. To be able to benchmark them, add a new argument to benchmarks to enable or disable endpoint error handling.

Add argument to enable/disable endpoint error handling in benchmarks

---

.github/workflows/build.yaml

Forward-merge triggered by push to `branch-0.35` that creates a PR to keep `branch-0.36` up-to-date. If this PR is unable to be immediately merged due to conflicts, it will remain open for the team to manually merge.

Forward-merge branch-0.35 to branch-0.36

---

ci/run_benchmark_pytests.sh
ci/run_pytests.sh
ci/test_python.sh
ci/test_wheel.sh

This PR adds an environment-agnostic `run_pytests.sh` script, and updates `test_python.sh` to call it.
The `test_python.sh` script assumes it's running in our CI environment, and it does more than just run pytest.
This PR allows devs and downstream consumers to only run the tests, and skip the unrelated logic in `test_python.sh`.

Add environment-agnostic scripts for running pytests

---

dependencies.yaml
docs/source/install.rst

Contributes to https://github.com/rapidsai/build-planning/issues/3
This PR adds support for Python 3.11.
This is part of ongoing work to add Python 3.11 support across RAPIDS.
The Python 3.11 CI workflows introduced in https://github.com/rapidsai/shared-workflows/pull/176 are *optional*... they are not yet required to run successfully for PRs to be merged.
This PR can be merged once all jobs are running successfully (including the non-required jobs for Python 3.11). The CI logs should be verified that the jobs are building and testing with Python 3.11.
See https://github.com/rapidsai/shared-workflows/pull/176 for more details.

Add support for Python 3.11

---

ci/test_wheel.sh

Add timeouts for CI wheel tests to prevent it from getting stuck if something fails in an unexpected way.

Add timeouts for CI wheel tests

---

ci/check_style.sh
ci/test_python.sh

conda dropped support for the `--force` flag to `conda env create`. This changes that flag name to `--yes`.
See https://github.com/conda/conda/blob/main/CHANGELOG.md#2430-2024-03-12 and https://github.com/rapidsai/miniforge-cuda/pull/63 for more info.

Use `conda env create --yes` instead of `--force`

---

debug-tests/client.py
tests/test_custom_send_recv.py
tests/test_send_recv_two_workers.py

https://github.com/rapidsai/cudf/pull/16063 has updated the import location of `assert_eq` to the public `cudf.testing.assert_eq`, this change updates imports accordingly.

Update cuDF's `assert_eq` import

---

ci/build_wheel.sh

For https://github.com/rapidsai/build-planning/issues/57, #1041 switched `ucx-py` over to `libucx` wheels. To test that that was working, it added some code to building scripts to remove system installations of UCX libraries.
That should no longer be necessary as of https://github.com/rapidsai/ci-imgs/pull/154.
This proposes removing that code for managing system dependencies of UCX libraries, to simplify those build scripts a bit.

remove management of UCX system libraries in build scripts

---

.github/workflows/build.yaml
.github/workflows/pr.yaml
.github/workflows/test.yaml
dependencies.yaml

This PR updates the latest CUDA build/test version 12.2.2 to 12.5.1.
Contributes to https://github.com/rapidsai/build-planning/issues/73

Build and test with CUDA 12.5.1

---

.pre-commit-config.yaml
ci/release/update-version.sh

With the deployment of rapids-build-backend, we need to make sure our dependencies have alpha specs.
Contributes to https://github.com/rapidsai/build-planning/issues/31

Use verify-alpha-spec hook

---

.readthedocs.yml
dependencies.yaml
pyproject.toml

Follow-up to #1057.
Implements the following suggestions based on review comments from @jakirkham and @bdice there:
* splits `cupy` out into its own list in `dependencies.yaml`, to allow removing some `cuda_suffixed: "false"` blocks that were otherwise redundant
* passes `--matrix-entry 'cuda=12.x'` in docs builds, to make it clearer that those builds are just trying to match `cuda: "12.*"` and are not at all dependent on any particular minor version of CUDA
Also proposes defaulting to `cupy-cuda12x` in `pyproject.toml`, as part of https://github.com/rapidsai/build-planning/issues/68.

refactor dependency-file-generator handling of cupy, default to CUDA 12 in fallback dependency lists

---

ci/release/update-version.sh

Script errors with `ci/release/update-version.sh: line 45: NEXT_SHORT_TAG_PEP440: unbound variable`
I updated the usages of `NEXT_SHORT_TAG_PEP440` to `NEXT_RAPIDS_SHORT_TAG_PEP440` (the RAPIDS version).
I also renamed `NEXT_RAPIDS_FULL_TAG_PEP440` to `NEXT_FULL_TAG_PEP440` which it actually the ucx-py version.
Tested locally.

Fix naming in update-version

---

.pre-commit-config.yaml

Since the --rapids-version argument will change from one release to the next, use a block style instead of a flow style to make merge conflicts less likely.

Use block style instead of flow style for pre-commit hook

---

dependencies.yaml
docker/ucx-py-cuda11.5.yml
docs/source/install.rst
pyproject.toml

Contributes to https://github.com/rapidsai/build-planning/issues/88
Finishes the work of dropping Python 3.9 support.
This project stopped building / testing against Python 3.9 as of https://github.com/rapidsai/shared-workflows/pull/235.
This PR updates configuration and docs to reflect that.
Checked that there were no remaining uses like this:
```shell
git grep -E '3\.9'
git grep '39'
git grep 'py39'
```
And similar for variations on Python 3.8 (to catch things that were missed the last time this was done).

Drop Python 3.9 support

---

.github/workflows/build.yaml
.github/workflows/pr.yaml
.github/workflows/test.yaml
dependencies.yaml
docs/source/install.rst

Contributes to https://github.com/rapidsai/build-planning/issues/40
This PR adds support for Python 3.12.
This is part of ongoing work to add Python 3.12 support across RAPIDS.
It temporarily introduces a build/test matrix including Python 3.12, from https://github.com/rapidsai/shared-workflows/pull/213.
A follow-up PR will revert back to pointing at the `branch-24.10` branch of `shared-workflows` once all
RAPIDS repos have added Python 3.12 support.
CI here is expected to fail until all of this project's upstream dependencies support Python 3.12.
This can be merged whenever all CI jobs are passing.

WIP: Add support for Python 3.12

---

.flake8
.pre-commit-config.yaml

We need to update flake8 to fix a false-positive that appears with older flake8 versions on Python 3.12.
I also combined the flake8-cython configuration by using flake8-force. We have adopted this in all other RAPIDS repos, but it seems ucx-py was overlooked.

Update flake8 to 7.1.1.

---

ci/test_python.sh

Contributes to https://github.com/rapidsai/build-planning/issues/106
Proposes specifying the RAPIDS version in `conda install` calls that install CI artifacts, to reduce the risk of CI jobs picking up artifacts from other releases.

make conda installs in CI stricter

---

ucp/_libs/arr.pyx

These are all pure C functions implemented in Cython. They do not raise. Cython 3 adds checks for exceptions in these functions, which is unnecessary given none of these set exceptions. So add `noexcept` to turn off these Cython checks.
xref: https://github.com/rapidsai/kvikio/pull/502

Mark all `nogil` `cdef` functions as `noexcept`

---

docs/source/ucx-debug.rst

Changes the example output here to use Miniforge.

Use Miniforge path in UCX debugging example

---

ucp/_libs/arr.pyx

In `Array`, `Py_ssize_t[::1]` objects are currently backed by [CPython `array`'s]( https://cython.readthedocs.io/en/latest/src/userguide/memoryviews.html#cpython-array-module ) with some internal bits expressed in Cython. However these are not compatible with [Python's Limited API and Stable ABI]( https://docs.python.org/3/c-api/stable.html#c-api-stability ). To address that, switch to [Cython's own `array` type]( https://cython.readthedocs.io/en/latest/src/userguide/memoryviews.html#cython-arrays ). As this is baked into Cython and doesn't use anything special, it is compatible with Python's Limited API and Stable ABI.
xref: https://github.com/rapidsai/build-planning/issues/42

Use Cython's `array` to back `Py_ssize_t[::1]`

---

.pre-commit-config.yaml
ci/build_python.sh
ci/build_wheel.sh

Contributes to https://github.com/rapidsai/build-planning/issues/111
Proposes some small packaging/CI changes, matching similar changes being made across RAPIDS.
* updating to the latest `rapids-dependency-file-generator` (v1.16.0)
* removing unnecessary calls to `rapids-configure-sccache` (this project does not use `sccache`)
I'd originally started this PR with the goal of printing `sccache` stats in builds here... but realized this project does not use `sccache`.
I chose not to pursue adding `sccache` here. The fact that this project doesn't use CMake means it'd take some effort to figure out how to inject `sccache` into the compilation (`CC` / `CXX` environment variables? something else?). Conda and wheel builds are only spending around 20 seconds actually compiling Cython code, so it …

remove unnecessary sccache configuration, other small CI changes

---

ci/build_wheel.sh
ci/validate_wheel.sh
pyproject.toml

Contributes to https://github.com/rapidsai/build-planning/issues/110
Proposes adding 2 types of validation on wheels in CI, to ensure we continue to produce wheels that are suitable for PyPI.
* checks on wheel size (compressed),
- *to be sure they're under PyPI limits*
- *and to prompt discussion on PRs that significantly increase wheel sizes*
* checks on README formatting
- *to ensure they'll render properly as the PyPI project homepages*
- *e.g. like how https://github.com/scikit-learn/scikit-learn/blob/main/README.rst becomes https://pypi.org/project/scikit-learn/*

enforce wheel size limits, README formatting in CI

---

docs/source/install.rst

Contributes to https://github.com/rapidsai/build-planning/issues/118
Caused by https://github.com/rapidsai/ucx-wheels/pull/13
I originally came here to document the implications of https://github.com/rapidsai/ucx-wheels/pull/13 in the docs, namely:
* if you have a `libucx-cu{11,12}` wheel installed, then by default `ucx-py` will use UCX libraries from that wheel
* environment variable `RAPIDS_LIBUCX_PREFER_SYTEM_LIBRARY=true` can be set to opt out of this and use a system installation instead
While doing that, I noticed some other opportunities for improvement in the installation docs:
* updating build-UCX-from-source instructions to UCX 1.15 ([the oldest version this project now supports](https://github.com/rapidsai/ucx-py/blob/9efacc6069226de8e207177a359189f8880203a8/dependencies.yaml#L1 …

document changes in library-loading, update build-UCX-from-source docs

---

conda/recipes/ucx-py/conda_build_config.yaml

conda-forge is using GCC 13 for CUDA 12 builds. This PR updates CUDA 12 conda builds to use GCC 13, for alignment.
These PRs should be merged in a specific order, see https://github.com/rapidsai/build-planning/issues/129 for details.

Use GCC 13 in CUDA 12 conda builds.

---

ucp/core.py

Add support to configure the timeout of messages during exchange peer info via constructor argument and environment variable.
This feature is important in Distributed (see https://github.com/rapidsai/ucx-py/pull/994 for details), more so on larger scale clusters. A new configuration variable will be added to allow controlling this feature via Dask config and environment variables.

Expose configuration of exchange peer info timeout

---

dependencies.yaml
docker/ucx-py-cuda11.5.yml
pyproject.toml

Numba 0.61.0 just got released with couple of breaking changes, this pr is required to unblock the ci.
xref: https://github.com/rapidsai/cudf/pull/17777

Add upper bound to prevent usage of numba 0.61.0

---

conda/recipes/ucx-py/meta.yaml
dependencies.yaml

Increase upper UCX pin to 1.19 to allow us supporting UCX 1.18 that is needed for RAPIDS 25.02.

Increase upper UCX pin to 1.19

---

.pre-commit-config.yaml
ci/release/update-version.sh

Contributes to https://github.com/rapidsai/build-planning/issues/136
This project's `update-version.sh` misses some RAPIDS dependencies in `pyproject.toml`. This fixes that.
Also updates to the latest `rapids-dependency-file-generator`.
```shell
git fetch upstream --tags
./ci/release/update-version.sh '0.43.00'
git grep -E '25\.2'
git grep -E '25\.02'
git grep -E '0\.42'
```

ensure update-version.sh updates pyproject.toml

---

.pre-commit-config.yaml
ci/build_wheel.sh
ci/test_python.sh
ci/test_wheel.sh

Uses a retry wrapper for `pip` commands to try to alleviate CI failures due to hash mismatches that result from network hiccups
xref rapidsai/build-planning#148
This will retry failures that show up in CI like:
```
Collecting nvidia-cublas-cu12 (from libraft-cu12==25.2.*,>=0.0.0a0)
Downloading https://pypi.nvidia.com/nvidia-cublas-cu12/nvidia_cublas_cu12-12.8.3.14-py3-none-manylinux_2_27_aarch64.whl (604.9 MB)
━━━━━━━━━━━━━━━━━━━━━                 350.2/604.9 MB 229.2 MB/s eta 0:00:02
ERROR: THESE PACKAGES DO NOT MATCH THE HASHES FROM THE REQUIREMENTS FILE. If you have updated the package versions, please update the hashes. Otherwise, examine the package contents carefully; someone may have tampered with them.
nvidia-cublas-cu12 from …
```

Use `rapids-pip-retry` in CI jobs that might need retries

---

conda/environments/builddocs.yml

Contributes to https://github.com/rapidsai/build-planning/issues/155
Fixes docs builds by temporarily putting a ceiling on `sphinx`.
In case you're wondering why you don't see `dependencies.yaml` changes... this project uses readthedocs to builds its docs.
* builds: https://app.readthedocs.org/projects/ucx-py/builds/
* config: https://github.com/rapidsai/ucx-py/blob/674e731c21e3a85045239a943248b23dab019619/.readthedocs.yml#L16-L17

require sphinx<8.2.0

---

ucp/__init__.py

With protov1 not being actively developed anymore and protov2 now being more stable, it's time to switch permanently. See https://github.com/rapidsai/ucx-py/issues/1121 for more details.
Closes https://github.com/rapidsai/ucx-py/issues/1121 .

Enable protov2 by default on UCX >= 1.18.0

---

.github/workflows/build.yaml
.github/workflows/pr.yaml
ci/test_python.sh
ci/test_wheel.sh

This work is towards moving build artifacts from `downloads.rapids.ai` to Github Artifact Store (see https://github.com/rapidsai/ops/issues/2982)
Updates conda and wheel artifact download source from S3 to GitHub across CI scripts, wherever applicable. 
Uses dynamic temporary paths for wheel downloads returned by `rapids-download-wheels-from-github` instead of using fixed directories, to streamline wheel downloads in the same way as conda downloads.
Also updates CI workflows to follow `package-name` convention between wheel build and wheel publish jobs.

Download build artifacts from Github for CI

---

.github/workflows/build.yaml
.github/workflows/pr.yaml
.github/workflows/test.yaml
.github/workflows/trigger-breaking-change-alert.yaml
dependencies.yaml
docs/source/install.rst

This PR uses CUDA 12.9.0 to build and test.
xref: https://github.com/rapidsai/build-planning/issues/173

Build and test with CUDA 12.9.0

---

conda/recipes/ucx-py/recipe.yaml

This quotes `head_rev` to ensure that commits with leading zeros in the git SHA include those zeros in the output package name.
xref: https://github.com/rapidsai/build-planning/issues/176

Quote head_rev in conda recipes

---

.github/workflows/build.yaml
.github/workflows/pr.yaml
.github/workflows/test.yaml
.github/workflows/trigger-breaking-change-alert.yaml
docs/source/install.rst

This PR reverts shared-workflows branches to `branch-25.06` and ensures builds use CUDA 12.8.
CUDA 12.9 will be used in the test matrix but not for builds in RAPIDS 25.06. See https://github.com/rapidsai/build-planning/issues/173#issuecomment-2882179838 for more information.

Finish CUDA 12.9 migration and use branch-25.06 workflows

---

.github/workflows/build.yaml
.github/workflows/pr.yaml
.github/workflows/test.yaml
ci/build_wheel.sh
ci/test_wheel.sh

Proposes a batch of small, mostly-unrelated changes to building and packaging.
These are all part of RAPIDS-wide efforts to make it easier to reproduce CI locally and to use artifacts from one project's CI in another project's CI.
Contributes to https://github.com/rapidsai/shared-workflows/issues/356
* explicitly provides an input for `script` to workflows using it, instead of relying on a default value coming from the workflow file
Contributes to https://github.com/rapidsai/build-planning/issues/179
* adds a call to `rapids-init-pip` near the beginning of all CI scripts that use `pip`
Contributes to https://github.com/rapidsai/gha-tools/issues/145
* confirmed that `rapids-configure-conda-channels` is not used in any builds scripts using `rattler-build`

use 'rapids-init-pip' in wheel CI, other CI changes

---

ci/build_python.sh
ci/build_wheel.sh

Contributes to https://github.com/rapidsai/build-planning/issues/181
* removes all uploads of conda packages and wheels to `downloads.rapids.ai`
Looked for uses of the relevant `gha-tools` tools, as well as documentation about `downloads.rapids.ai`, being on the NVIDIA VPN, using S3, etc. like this:
```shell
git grep -i -E 's3|upload|downloads\.rapids|vpn'
```
See "How I tested this" on https://github.com/rapidsai/shared-workflows/pull/364

stop uploading packages to downloads.rapids.ai
