- Makefile
Reverts Akshay-Venkatesh/ucx-py#53
> Revert "Use conda-build's Python"

- ucp/_libs/src/ucp_py_ucp_fxns.c
- ucp/_libs/ucp_py.pyx
@mrocklin FLUSH_MODE addresses the request you had in #81
> flush mode for ep close

- tests/client-server-duality.py
- tests/future-recv-fast.py
- tests/send-recv-py-obj.py
- tests/test_buffer_region.py
- tests/test_no_cuda.py
- ucp/_libs/ucp_py.pyx
- ucp/_libs/ucp_py_buffer_helper.pyx
Addressing python naming concerns raised in issue #24 raised by @mrocklin - Note that name changes require changes in the ucx-based dask code (calls to `ucp.ucp_py_ep` need to be changed to `ucp.EndPoint`).  I will submit a PR to that repository if/when these changes are accepted.
> Camelcase fixes

- tests/test_init_fin.py
- ucp/_libs/ucp_py.pyx
> Allow ucp init() and fin() to be called multiple times

- ucp/_libs/ucp_py.pyx
- basic logging for now
- may extend this to capture timing information
> log basic resource init/fin and transfer functions

- ucp/_libs/ucp_py.pyx
> Hold a reference to listener futures to avoid garbage collection

- tests/test_addr.py
- ucp/_libs/ucp_py.pyx
This should help when debugging
> Add Endpoint.__str__ implementation

- tests/test_send_recv_obj.py
- ucp/_libs/src/ucp_py_ucp_fxns.c
- ucp/_libs/src/ucp_py_ucp_fxns.h
- ucp/_libs/ucp_py.pyx
- ucp/_libs/ucp_py_ucp_fxns_wrapper.pyx
- ucp/_utils.py
- add fd reader at init and remove at finalize
- add a seperate fxn to get ucp_worker fd
- minor changes in `test_send_recv_obj.py` and `utils.py`
> fd reader cleanup

- README.md
Fixes https://github.com/rapidsai/ucx-py/issues/132
This is mostly copy-pasta from the original instructions. Feel free to adjust as needed.
cc @mrocklin
> Explain how to install preliminary Conda packages

- tests/test_buffer_region.py
- ucp/_libs/ucp_py_buffer_helper.pyx
PR supersedes https://github.com/rapidsai/ucx-py/pull/50
Thank @TomAugspurger !
> fix 0 length arrays

- ucp/_libs/ucp_py_buffer_helper.pyx
@kkraus14 suggested using `__dealloc__` method to plug the leak that was identified with use of BufferRegion objects which allocate memory for incoming receives with `recv_obj` method. Previously the leak appeared in the following way with `test_send_recv_obj.py` test
```bash
$ UCX_RNDV_SCHEME=put_zcopy UCX_MEMTYPE_CACHE=n UCX_TLS=rc,cuda_copy,cuda_ipc cuda-memcheck
--leak-check full py.test -vs tests/test_send_recv_obj.py::test_send_recv_numba[67108864]
========= CUDA-MEMCHECK
================================================== test session starts ===================================================
platform linux -- Python 3.7.2, pytest-4.3.0, py-1.8.0, pluggy-0.9.0 -- /home/akvenkatesh/py/install/bin/python3
cachedir: .pytest_cache
rootdir: /home/akvenkatesh/ucx-py, inifile:
plugins: …
```
> Free mem allocated by BufferRegion for recv after going out of scope

- benchmarks/recv-into-client.py
I'm not sure exactly why there's hang when I run `asyncio.run(main())`  [here](https://github.com/rapidsai/ucx-py/compare/fix-recv-into-benchmark?expand=1#diff-c9e616aa2908e76e06ec256178d32899L154) as opposed to getting event loop and having that loop run the coroutine returned by server and client. My guess is that the event loop used [here](https://github.com/rapidsai/ucx-py/blob/devel/ucp/_libs/ucp_py.pyx#L649) and the event loop used when just calling `asyncio.run(...)` may be different.
> explicit event loop usage

- ucp/_libs/ucp_py.pyx
Depend on #152
Simplifying by removing duplicate code.
> ucp cleanup

- tests/test_custom_ep_send_recv.py
PR fixes an error in the custom ep test
> small change to custom ep test

- ucp/_libs/src/ucp_py_ucp_fxns.c
> updates from @akshay wrt to TCP error handling

- ucp/_libs/core.pyx
- ucp/_libs/core_dep.pxd
- ucp/_libs/src/c_util.c
- ucp/_libs/src/c_util.h
This PR fixes a memory leak of `_listener_callback_args` and checks every `malloc` for _out of memory_.
> [REVIEW] Malloc check and leak fix

- tests/test_send_recv_cudf.py
Resolves https://github.com/rapidsai/ucx-py/issues/207
> [REVIEW] Test CUDF

- ucp/_libs/utils.pyx
> Buffer contiguous check

- tests/test_shutdown.py
- ucp/_libs/core.pyx
> Implementing Listener.close()

- tests/test_send_recv.py
- ucp/_libs/core.pyx
- ucp/_libs/core_dep.pxd
- ucp/_libs/send_recv.pyx
This PR adds extra information on communication error, which easy debugging.
And adds message length checks.
> More Information on Communication Error

- README.md
- docs/source/deployment.rst
- docs/source/index.rst
I've added a section to the README about `NVLink and Docker/Kubernetes` to explain how to use NVLink when using containers to isolate/deploy processes.
I've also corrected markdown linting issues and spelling/grammar generally.
> Add container NVLink section and lint file

- tests/test_send_recv.py
- ucp/_libs/core.pyx
- ucp/public_api.py
This PR implements a `guarantee_msg_order` argument when creating Endpoints, which UCX tag messaging [doesn't guarantees](https://github.com/dask/distributed/pull/3135#issuecomment-545480041).
> Non blocking UCX progress mode

- README.md
> Revert "Add ReadTheDocs badge to the README" [skip ci]

- README.md
Resubmission of PR ( https://github.com/rapidsai/ucx-py/pull/302 )
cc @dillon-cullinan
> Add ReadTheDocs badge to the README (pt. 2)

- examples/cudf-example.py
- examples/cupy-example.py
> [DRAFT] Add Examples

- docs/source/configuration.rst
> add IPC env var to docs

- README.md
This adds our Cython requirement to our README. Hopefully helps out users installing this from source.
> Document Cython requirement

- README.md
This pr just fixes the the distributed repo url .
> [REVIEW] Fix distributed repo url in readme

- docs/source/quickstart.rst
> Doc Update - Add NumPy Example

- docs/source/dask.rst
- docs/source/index.rst
- examples/cudf-example.py
- examples/cupy-example.py
This PR adds documentation on using dask with UCX
cc @jakirkham @pentschev
> UCX + Dask Doc

- ci/gpu/build.sh
> Ci check distributed

- docs/source/configuration.rst
closes https://github.com/rapidsai/ucx-py/issues/221
@madsbk if you have time can you review ?
> add-configure-doc

- docs/source/install.rst
> add conda env in sourc install instructions

- ci/release/update-version.sh
- ucp/__init__.py
Auto-merge triggered by push to `branch-0.11` that creates a PR to keep `branch-0.12` up-to-date. If this PR is unable to be immediately merged due to conflicts, it will remain open for the team to manually merge.
> [gpuCI] Auto-merge branch-0.11 to branch-0.12 [skip ci]

- docs/source/api.rst
- docs/source/quickstart.rst
This PR updates the API section of the docs
> Update API section

- README.md
- ci/gpu/build.sh
- ci/release/update-version.sh
- docs/source/conf.py
- docs/source/configuration.rst
- docs/source/install.rst
- docs/source/quickstart.rst
- ucp/__init__.py
- ucp/_libs/topological_distance.pyx
Only critical/hotfix level issues should be merged into `branch-0.11` until release (merging of this PR).
- Update documentation
- Allow testing for the new release
- Enable a means to merge `branch-0.11` into `master` for the release
> [RELEASE] v0.11 ucx-py

- ucp/_libs/topological_distance.pyx
> Use __dealloc__ for TopologicalDistance Cython code

- ucp/_libs/send_recv.pyx
Type the argument of the send/recv functions to make them a bit clearer and simpler.
> Type send/recv functions

- benchmarks/cudf-merge.py
- tests/test_send_recv_two_workers.py
Use RMM `DeviceBuffer` for allocations.
> Use RMM's DeviceBuffer (in cudf-merge and elsewhere)

- conda/environments/builddocs_py37.yml
Fixes https://github.com/rapidsai/ucx-py/issues/349
> Update doc environment file

- benchmarks/local-send-recv.py
- ucp/__init__.py
Auto-merge triggered by push to `branch-0.12` that creates a PR to keep `branch-0.13` up-to-date. If this PR is unable to be immediately merged due to conflicts, it will remain open for the team to manually merge.
> [gpuCI] Auto-merge branch-0.12 to branch-0.13 [skip ci]

- ci/gpu/build.sh
- docs/source/conf.py
> Test GPU specific serialization protocols on CI

- docs/source/configuration.rst
> add section on rndv-thresh

- benchmarks/cudf-merge.py
This fix is ready to be merged
> [MERGE] Fixed the cudf-merge benchmark

- ucp/_libs/core.pyx
This change will get a random port number without creating a socket on it, that sometimes prevents a dask worker from starting due to the socket being in a `TIME_WAIT` state.
We would see messages like the one below:
```
[1583153840.078159] [dgx12:67177:0]   ucp_listener.c:431  UCX  ERROR none of the available transports can listen for connections on 0.0.0.0:41245
```
and ultimately leading the start of a dask worker to fail with the following traceback:
```python-traceback
Traceback (most recent call last):
File "/home/pentschev/miniconda3/envs/rn-101-0.13.0b200301/bin/dask-cuda-worker", line 8, in <module>
sys.exit(go())
File "/home/pentschev/miniconda3/envs/rn-101-0.13.0b200301/lib/python3.7/site-packages/dask_cuda/dask_cuda_worker.py", line 382, in go
main()
File …
```
> Use psutil instead of socket to get a random port number

- docs/source/configuration.rst
- ucp/__init__.py
https://github.com/rapidsai/ucx-py/issues/424
cc @pentschev
> Add default values for rndv_thresh rx/tx seg size and update docs

- ucp/_libs/core.pyx
> Support host names

- ci/gpu/build.sh
Auto-merge triggered by push to `branch-0.13` that creates a PR to keep `branch-0.14` up-to-date. If this PR is unable to be immediately merged due to conflicts, it will remain open for the team to manually merge.
> [gpuCI] Auto-merge branch-0.13 to branch-0.14 [skip ci]

- ucp/_libs/core.pyx
- ucp/_libs/send_recv.pyx
Fixes #435, fixes #432, and replaces #436.
> Error handling of void returning cython functions

- tests/test_custom_send_recv.py
- tests/test_reset.py
- tests/test_send_recv.py
The PR backport some test fixes from #418
> Backporting test fixes from #418

- ci/gpu/build.sh
> Pin RAPIDS packages to `${MINOR_VERSION}`

- ucp/_libs/core.pyx
- ucp/continuous_ucx_progress.py
- ucp/public_api.py
This PR moves ucx progress in its own file and use classes to simplify the clean up process.
> [REVIEW] Clean up of UCX progress

- docs/source/conf.py
Should fix the style error seen in PR ( https://github.com/rapidsai/ucx-py/pull/469 ).
cc @madsbk
> Run `black` on `docs/source/conf.py`

- ci/gpu/build.sh
Includes the RMM tests and slow UCX tests from Distributed as well.
> Run more Distributed UCX tests on CI

- tests/test_guarantee_msg_order.py
> Catching server side error in guarantee msg order test 

- ucp/_libs/core.pyx
Implementing `CtrlMsg` using the `struct` module instead of cython's struct.
This PR is part of the effort to restrict the use of Cython to `ucx_api.pyx`
>  Implementing CtrlMsg using struct

- setup.py
Fixes https://github.com/rapidsai/ucx-py/issues/146
> List Python install requirements

- tests/test_disconnect.py
- tests/test_send_recv.py
- ucp/_libs/ucx_api.pyx
- ucp/core.py
- ucp/exceptions.py
This PR fixes #491. I am working on testing this case.
@beckernick can I get you to see if this helps?
> Fix error logging when closing peer endpoint

- ucp/_libs/ucx_api.pyx
- ucp/_libs/utils.pyx
- ucp/core.py
- ucp/utils.py
Added checksum of the message exchange in `exchange_peer_info()`
cc. @pentschev
> Endpoint sanity check

- docs/source/configuration.rst
> Update configuration parameters in documentation

- ci/gpu/build.sh
PR adds a test for nanny closure from Distributed
xref https://github.com/dask/distributed/pull/3747
@rapidsai/admins can you review and merge ?
> Test Distributed Nannies

- docs/source/conf.py
- setup.cfg
* Make sure the `v` prefix is stripped from the version
* Use `versioneer` to generate the version in the docs
> Fix-up versioneer

- ucp/_libs/src/c_util.c
> Set connection endpoint flag to no loopback

- ucp/core.py
Simplify this step by switching from `struct.pack`/`struct.unpack` to `array`. This way we can easily create a singleton `array` of the right type and fill it with the result to send over the wire.
> Use `array` to send/recv `nbytes`

- ci/gpu/build.sh
- setup.py
Auto-merge triggered by push to `branch-0.15` that creates a PR to keep `branch-0.16` up-to-date. If this PR is unable to be immediately merged due to conflicts, it will remain open for the team to manually merge.
> [gpuCI] Auto-merge branch-0.15 to branch-0.16 [skip ci]

- docs/source/install.rst
update install instructions for cuda 11 and remove 9.2./10.0
> [skip ci] CUDA Doc Update

- ucp/_libs/utils.pyx
Leverages the `Py_buffer` object held by `memoryview` objects to perform some computations and checks in C. Also gets the `memoryview` using `PyMemoryView_FromObject`, which has less overhead.
> Use Python C API in util functions w/host buffers

- docs/source/install.rst
Follow up for https://github.com/rapidsai/ucx-py/issues/628#issuecomment-702415714
cc @pentschev
> doc update for only applying the patches when using cuda

- benchmarks/local-send-recv.py
- docs/source/install.rst
- docs/source/quickstart.rst
- tests/test_send_recv.py
Auto-merge triggered by push to `branch-0.16` that creates a PR to keep `branch-0.17` up-to-date. If this PR is unable to be immediately merged due to conflicts, it will remain open for the team to manually merge.
> [gpuCI] Auto-merge branch-0.16 to branch-0.17 [skip ci]

- docs/source/index.rst
- docs/source/ucx-debug.rst
Very early work on writing down all the diagnostics we have utilized in uncovering performance issues and/or configurations issues
> [REVIEW] UCX/UCX-Py Debugging/Performance checks

- ci/gpu/build.sh
Specify `master` branch to bypass `pip` solver
> Fix `pip install` issues w/new resolver

- README.md
- ci/gpu/build.sh
- docs/source/configuration.rst
- ucp/__init__.py
Auto-merge triggered by push to `branch-0.17` that creates a PR to keep `branch-0.18` up-to-date. If this PR is unable to be immediately merged due to conflicts, it will remain open for the team to manually merge.
> [gpuCI] Auto-merge branch-0.17 to branch-0.18 [skip ci]

- README.md
- benchmarks/local-send-recv.py
- ci/gpu/build.sh
- docs/source/configuration.rst
- tests/test_disconnect.py
- ucp/__init__.py
- ucp/_libs/topological_distance.pxd
- ucp/_libs/topological_distance.pyx
- ucp/_libs/ucx_api.pyx
- ucp/core.py
- ucp/endpoint_reuse.py
Only critical/hotfix level issues should be merged into `branch-0.17` until release (merging of this PR).
- Update documentation
- Allow testing for the new release
- Enable a means to merge `branch-0.17` into `main` for the release
> [RELEASE] ucx-py v0.17

- ucp/_libs/ucx_api.pyx
Auto-merge triggered by push to `branch-0.18` that creates a PR to keep `branch-0.19` up-to-date. If this PR is unable to be immediately merged due to conflicts, it will remain open for the team to manually merge.
> [gpuCI] Auto-merge branch-0.18 to branch-0.19 [skip ci]

- docs/source/deployment.rst
- docs/source/ucx-debug.rst
> fix typo and add note on sockcm error

- ucp/_libs/src/c_util.c
- ucp/_libs/src/c_util.h
- ucp/_libs/ucx_api.pyx
- ucp/_libs/ucx_api_dep.pxd
Minimize the use of pure C
This PR is part **2** of an effort to merge https://github.com/rapidsai/ucx-py/pull/648 in a divide-and-conquer approach.
> Cleanup low-level UCX options

- tests/test_rma.py
- tests/test_ucx_api.py
- ucp/_libs/ucx_api.pyx
- ucp/_libs/ucx_api_dep.pxd
Minimize the use of pure C
This PR is part **3** of an effort to merge https://github.com/rapidsai/ucx-py/pull/648 in a divide-and-conquer approach.
> Redesign of UCXAddress and implementation of ep_create_from_address() 

- docs/source/index.rst
- docs/source/os-limits.rst
This PR adds a new RTD section to document some known issues that may arise due to OS limits.
> Document OS limits

- ucp/_libs/ucx_api.pyx
This PR helps deduplicate some code on handling file descriptors to get UCP info that's only available as text. On a future PR these functions will be used more as we introduce support to get also context and worker text information.
> Add new text file descriptor helper functions

- .flake8
- ucp/_libs/tests/test_config.py
- ucp/_libs/tests/test_peer_send_recv.py
- ucp/_libs/tests/test_server_client.py
- ucp/_libs/ucx_api.pyi
- ucp/_libs/ucx_api.pyx
- ucp/_libs/ucx_api_dep.pxd
This PR implements UCX features (the `UCP_FEATURE_*` constants) as Python Enum
> Feature flags as Python Enum

- docs/source/os-limits.rst
Forward-merge triggered by push to `branch-0.19` that creates a PR to keep `branch-0.20` up-to-date. If this PR is unable to be immediately merged due to conflicts, it will remain open for the team to manually merge.
> [gpuCI] Forward-merge branch-0.19 to branch-0.20 [skip ci]

- .pre-commit-config.yaml
Update package versions in pre-commit hook script.
> Update pre-commit hook script

- ucp/_libs/ucx_api.pyi
Update stub file `ucx_api.pyi` to reflect recent changes.
> Update ucx_api.pyi stub

- setup.py
This PR lets CI fail on compile warnings and fixes all current warnings.
> Compiling with compile flag "-Werror"

- ucp/_libs/tests/test_config.py
- ucp/_libs/tests/test_server_client_am.py
- ucp/_libs/utils_test.py
This PR addresses one of the shortcomings of the AM support, which is the lack of tests for low-level ucx_api.
> Add ucx_api tests for AM

- debug-tests/test_endpoint_error_callback.py
- tests/test_custom_send_recv.py
- tests/test_disconnect.py
- tests/test_info.py
- tests/test_shutdown.py
- ucp/_libs/tests/test_config.py
- ucp/_libs/tests/test_mem.py
- ucp/_libs/tests/test_peer_send_recv.py
- ucp/_libs/tests/test_server_client.py
- ucp/_libs/tests/test_server_client_am.py
- ucp/_libs/transfer_stream.pyx
- ucp/_libs/transfer_tag.pyx
- ucp/_libs/ucx_api_dep.pxd
- ucp/_libs/ucx_endpoint.pyx
- ucp/_libs/ucx_worker.pyx
- ucp/_libs/ucx_worker_cb.pyx
- ucp/core.py
- ucp/exceptions.py
Forward-merge triggered by push to `branch-21.06` that creates a PR to keep `branch-21.08` up-to-date. If this PR is unable to be immediately merged due to conflicts, it will remain open for the team to manually merge.
> [gpuCI] Forward-merge branch-21.06 to branch-21.08 [skip ci]

- benchmarks/local-send-recv.py
Forward-merge triggered by push to `branch-0.20` that creates a PR to keep `branch-0.21` up-to-date. If this PR is unable to be immediately merged due to conflicts, it will remain open for the team to manually merge.
> [gpuCI] Forward-merge branch-0.20 to branch-0.21 [skip ci]

- ucp/_libs/ucx_worker.pyx
This doesn't seem particularly harmful but will print error messages such as below when `UCP_FEATURE_TAG` isn't enabled:
```
[1622725568.485158] [dgx15:10298:0]           probe.c:30   UCX  ERROR feature flags UCP_FEATURE_TAG were not set for ucp_init()
```
> Don't drain TAG messages when UCP_FEATURE_TAG isn't enabled

- ci/gpu/build.sh
Forward-merge triggered by push to `branch-0.21` that creates a PR to keep `branch-0.22` up-to-date. If this PR is unable to be immediately merged due to conflicts, it will remain open for the team to manually merge.
> [gpuCI] Forward-merge branch-0.21 to branch-0.22 [skip ci]

- tests/test_config.py
Starting from UCX 1.12, it's not possible to validate non-UCP configuration options, update tests accordingly.
See https://github.com/openucx/ucx/issues/7519 .
> Update UCP configuration validation tests for UCX >= 1.12

- ucp/_libs/ucx_rkey.pyx
Resolve UCX warnings such as:
```
[1636059854.502867] [1a7f04145417:10924:0]           mpool.c:44   UCX WARN  object 0x5556f078ab40 was not returned to mpool ucp_rkeys
[1636059854.501943] [1a7f04145417:10998:0]           mpool.c:44   UCX WARN  object 0x55bafa4cdc40 was not returned to mpool ucp_rkeys
```
Downgrade UCX-Py assertion errors to debug logs:
```
Traceback (most recent call last):
File "/workspace/ucp/exceptions.py", line 13, in log_errors
yield
File "ucp/_libs/transfer_common.pyx", line 55, in ucp._libs.ucx_api._send_callback
cb_func(req, exception, *cb_args, **cb_kwargs)
File "ucp/_libs/ucx_rkey.pyx", line 13, in ucp._libs.ucx_api._ucx_remote_mem_finalizer_post_flush
assert exception is None
AssertionError
```
> Ensure rkey is destroyed when flush callback isn't called

- docs/source/transport-monitoring.rst
> Add new monitor line for nvlink and deprecate old one

- ucp/_libs/exceptions.py
- ucp/_libs/transfer_stream.pyx
- ucp/_libs/ucx_api_dep.pxd
> UCP: Handle UCS_ERR_UNREACHABLE status in stream recv callback

- docs/source/transport-monitoring.rst
> Fix transport doc

- docs/source/configuration.rst
- ucp/__init__.py
Forward-merge triggered by push to `branch-0.24` that creates a PR to keep `branch-0.25` up-to-date. If this PR is unable to be immediately merged due to conflicts, it will remain open for the team to manually merge.
> [gpuCI] Forward-merge branch-0.24 to branch-0.25 [skip gpuci]

- ucp/__init__.py
Separate PyNVML exceptions from the `ImportError` one, which fails if PyNVML couldn't be imported.
Fixes #847
> Fix for PyNVML `ImportError`

- ucp/__init__.py
Importing UCX-Py currently fails when trying to query memory for memory with PyNVML. Since it's not clear and not tested what would be safe `UCX_CUDA_COPY_MAX_REG_RATIO` values for MIG instances, just skip them and rely on UCX's default for now.
> Ignore MIG instances when overriding `UCX_CUDA_COPY_MAX_REG_RATIO`

- ucp/_libs/ucx_context.pyx
Forward-merge triggered by push to `branch-0.26` that creates a PR to keep `branch-0.27` up-to-date. If this PR is unable to be immediately merged due to conflicts, it will remain open for the team to manually merge.
> [gpuCI] Forward-merge branch-0.26 to branch-0.27 [skip gpuci]

- ci/gpu/build.sh
Closes https://github.com/rapidsai/ucx-py/issues/855
> Install Dask from nightly channel in CI build

- .github/ops-bot.yaml
We need this for building wheels.
> Reenable the ops bot.

- .github/workflows/build.yaml
- .github/workflows/pr.yaml
- .github/workflows/test.yaml
- .pre-commit-config.yaml
- ci/build_python.sh
- ci/check_style.sh
- ci/cpu/build.sh
- ci/gpu/build.sh
- ci/release/update-version.sh
- ci/test_python.sh
- conda/recipes/ucx-py/meta.yaml
- dependencies.yaml
This PR adds GitHub Actions workflows to `ucx-py`.
> Add GitHub Actions Workflows

- .github/workflows/build.yaml
- .github/workflows/pr.yaml
- .github/workflows/test.yaml
- .pre-commit-config.yaml
This PR updates the branch reference used for our shared workflows.
> Update shared workflow branches

- conda/recipes/ucx-py/conda_build_config.yaml
This PR updates builds to use GCC 11.
> Update to GCC 11

- .github/build-scripts/patch-wheel.sh
- .github/workflows/build.yaml
- .github/workflows/pr.yaml
- .github/workflows/test.yaml
Update wheel builds to use the new version of the workflow.
> Build wheels using new single image workflow

- .github/workflows/build.yaml
In #944 I updated the pr workflow to the new shared workflows branch but I didn't properly update the build workflow.
> Fix build workflow for new images

- docs/source/install.rst
> Resolve forward merger conflicts

- ucp/__init__.py
Closes https://github.com/rapidsai/ucx-py/issues/982
> Handle ``NVMLError_NotSupported`` exception

- ci/build_wheel.sh
- conda/recipes/ucx-py/conda_build_config.yaml
- conda/recipes/ucx-py/meta.yaml
- dependencies.yaml
- docker/Dockerfile
- docker/UCXPy-MOFED.dockerfile
- docker/UCXPy-rdma-core.dockerfile
- docker/build-ucx.sh
- docs/source/install.rst
- docs/source/ucx-debug.rst
Since UCX 1.15 `libnuma` is not used anymore and thus it should be removed. Additionally update dependency to `ucx>=1.15.0,<1.16`.
> Remove `libnuma`, update dependency to `ucx>=1.15.0,<1.16`

- ci/build_python.sh
This will make builds fail when there are path conflicts
> Prevent path conflict in builds

- ucp/__init__.py
Update version error message to match the minimum support UCX version and provide instructions to check where UCX is being loaded from.
Closes #1068 .
> Update version error message

- .github/workflows/build.yaml
- .github/workflows/pr.yaml
- .github/workflows/test.yaml
- .github/workflows/trigger-breaking-change-alert.yaml
- dependencies.yaml
- docs/source/install.rst
This PR uses CUDA 12.8.0 to build and test.
xref: https://github.com/rapidsai/build-planning/issues/139
> Build and test with CUDA 12.8.0

- dependencies.yaml
- docs/source/install.rst
Manual forward merge from 0.42 to 0.43. This PR should not be squashed.
> Forward-merge branch-0.42 into branch-0.43

- conda/recipes/ucx-py/recipe.yaml
- dependencies.yaml
- docs/source/install.rst
- pyproject.toml
Fixes forward merger xref #1130
> Forward-merge branch-0.44 into branch-0.45
